/**
 * Builds docs/VERIFICATION_SUITES.md from the suites themselves.
 *
 *   npm run docs:suites
 *
 * *** WHY THIS IS GENERATED AND NOT WRITTEN ***
 *
 * There are more than eighty `test:` scripts. A hand-written index of them
 * would be wrong within a week, and a wrong index is worse than none: someone
 * reads it, believes a suite covers something it does not, and skips the check.
 *
 * So the index is derived from each script's own header comment. The docstring
 * a person reads when they open the file IS the description — they cannot drift
 * apart, because there is only one of them.
 *
 * *** WHAT IT ASKS OF A SUITE ***
 *
 * A one-line summary at the top of the header, after the title. Suites with no
 * header are listed as undocumented rather than silently omitted, so the gap is
 * visible and shrinks as they get written.
 */

import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const OUT = path.join(ROOT, "docs", "VERIFICATION_SUITES.md");

type Suite = {
  script: string;
  file: string;
  title: string;
  summary: string;
};

/** The leading block comment, if the file opens with one. */
function headerComment(source: string): string | null {
  const match = /^\s*\/\*\*([\s\S]*?)\*\//.exec(source);
  if (!match) return null;
  return match[1]
    .split("\n")
    .map((line) => line.replace(/^\s*\*ilo?\s?/, "").replace(/^\s*\*\s?/, "").trimEnd())
    .join("\n")
    .trim();
}

/**
 * The title is the header's first line; the summary is the first prose
 * paragraph after it, skipping the usage line and any `***` section banner.
 */
function describe(header: string): { title: string; summary: string } {
  const lines = header.split("\n");
  const title = (lines[0] ?? "").trim();

  const body: string[] = [];
  for (const line of lines.slice(1)) {
    const trimmed = line.trim();
    if (!trimmed) {
      if (body.length > 0) break;
      continue;
    }
    if (trimmed.startsWith("***") || /^npm run /.test(trimmed)) {
      if (body.length > 0) break;
      continue;
    }
    body.push(trimmed);
  }

  return { title, summary: body.join(" ") };
}

const packageJson = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
  scripts: Record<string, string>;
};

const suites: Suite[] = [];
const undocumented: string[] = [];

for (const [script, command] of Object.entries(packageJson.scripts)) {
  if (!script.startsWith("test:")) continue;

  const match = /([\w./-]+\.(?:ts|mjs|cjs|js))/.exec(command);
  if (!match) continue;

  const file = match[1];
  const full = path.join(ROOT, file);
  if (!existsSync(full)) continue;

  const header = headerComment(readFileSync(full, "utf8"));
  if (!header) {
    undocumented.push(`${script} (${file})`);
    continue;
  }

  const { title, summary } = describe(header);
  suites.push({ script, file, title, summary });
}

suites.sort((a, b) => a.script.localeCompare(b.script));

const lines: string[] = [
  "# Verification suites",
  "",
  "**Generated by `npm run docs:suites` — do not edit by hand.**",
  "",
  "Each entry is the suite's own header comment. There is one description, in",
  "the file, so this index cannot drift away from what the suites actually do.",
  "",
  `${suites.length} documented, ${undocumented.length} without a header.`,
  "",
  "| Command | What it checks |",
  "|---|---|",
];

for (const suite of suites) {
  const what = suite.summary || suite.title;
  lines.push(
    `| \`npm run ${suite.script}\` | **${suite.title.replace(/\|/g, "\\|")}**<br>${what
      .replace(/\|/g, "\\|")
      .slice(0, 260)} |`,
  );
}

if (undocumented.length > 0) {
  lines.push(
    "",
    "## Without a header comment",
    "",
    "These run, but nothing in the file says what they are for. A suite whose",
    "purpose is undocumented is one nobody can safely change or delete.",
    "",
    ...undocumented.map((entry) => `- \`${entry}\``),
  );
}

lines.push("");

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"));

console.log("");
console.log(`  ${suites.length} suite(s) documented, ${undocumented.length} without a header`);
console.log(`  written to ${path.relative(ROOT, OUT)}`);
console.log("");
