/**
 * The user's working drafts, saved on their case (`master_result.drafts`).
 *
 * *** WHY THIS EXISTS (2026-10-04) ***
 *
 * Drafts lived only in the browser's localStorage (/document-workspace said so
 * on the page: "saved in this browser only"). Another device, a cleared
 * browser, or signing in again lost them. And the drafts were generated by an
 * engine that read an evidence store nothing fills any more, so most of what it
 * produced was boilerplate, with a settlement mode built to list "strengths,
 * weaknesses" — grading the case (CLAUDE.md section 3).
 *
 * A draft here is only what the user wrote or chose to start from: their own
 * story, their own timeline, their own intake answers, laid out under plain
 * headings for them to edit. Nothing in a draft is a model's prose, and
 * nothing in it judges the case.
 *
 * Pure: types, validation, and the starting points. The route that writes is
 * app/api/cases/drafts.
 */

export const MAX_DRAFTS = 30;
export const MAX_SECTIONS = 60;
export const MAX_TITLE_LENGTH = 200;
export const MAX_HEADING_LENGTH = 200;
export const MAX_SECTION_TEXT = 20_000;

export type DraftKind =
  | "blank"
  | "chronology"
  | "your-story"
  | "affidavit-outline"
  | "starting-document"
  | "imported";

export const DRAFT_KIND_LABELS: Record<DraftKind, string> = {
  blank: "Blank draft",
  chronology: "Chronology",
  "your-story": "Your story",
  "affidavit-outline": "Affidavit outline",
  "starting-document": "Starting document",
  imported: "Imported draft",
};

export type DraftSection = {
  id: string;
  heading: string;
  text: string;
  /** The user has read this part and marked it as checked. Theirs to set. */
  reviewed: boolean;
};

export type CaseDraft = {
  id: string;
  title: string;
  kind: DraftKind;
  createdAt: string;
  updatedAt: string;
  sections: DraftSection[];
};

const KINDS = Object.keys(DRAFT_KIND_LABELS) as DraftKind[];

const asRecord = (value: unknown): Record<string, unknown> =>
  value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};

const text = (value: unknown, max: number): string | null =>
  typeof value === "string" && value.length <= max ? value : null;

const ID = /^[A-Za-z0-9_-]{1,80}$/;

export function newId(prefix: string): string {
  const random =
    typeof crypto !== "undefined" && "randomUUID" in crypto
      ? crypto.randomUUID().replace(/-/g, "").slice(0, 16)
      : Math.random().toString(36).slice(2, 18);
  return `${prefix}_${random}`;
}

export type DraftValidation = { ok: true; draft: CaseDraft } | { ok: false; error: string };

/** Checks a draft from the client. Refuses rather than trims, so nothing is silently lost. */
export function validateDraft(raw: unknown, now: Date): DraftValidation {
  const input = asRecord(raw);
  const id = typeof input.id === "string" && ID.test(input.id) ? input.id : null;
  if (!id) return { ok: false, error: "The draft has no valid id." };
  const title = text(input.title, MAX_TITLE_LENGTH);
  if (title === null) return { ok: false, error: `A title can be up to ${MAX_TITLE_LENGTH} characters.` };
  const kind = KINDS.includes(input.kind as DraftKind) ? (input.kind as DraftKind) : null;
  if (!kind) return { ok: false, error: "Unknown kind of draft." };
  if (!Array.isArray(input.sections)) return { ok: false, error: "The draft has no sections." };
  if (input.sections.length > MAX_SECTIONS) return { ok: false, error: `A draft can have up to ${MAX_SECTIONS} parts.` };

  const sections: DraftSection[] = [];
  const seen = new Set<string>();
  for (const rawSection of input.sections) {
    const section = asRecord(rawSection);
    const sectionId = typeof section.id === "string" && ID.test(section.id) ? section.id : null;
    if (!sectionId || seen.has(sectionId)) return { ok: false, error: "A part of the draft has no valid id." };
    seen.add(sectionId);
    const heading = text(section.heading, MAX_HEADING_LENGTH);
    const body = text(section.text, MAX_SECTION_TEXT);
    if (heading === null) return { ok: false, error: `A heading can be up to ${MAX_HEADING_LENGTH} characters.` };
    if (body === null) return { ok: false, error: `One part is longer than ${MAX_SECTION_TEXT.toLocaleString()} characters.` };
    sections.push({ id: sectionId, heading, text: body, reviewed: section.reviewed === true });
  }

  const createdAt = typeof input.createdAt === "string" && !Number.isNaN(Date.parse(input.createdAt))
    ? input.createdAt
    : now.toISOString();

  return { ok: true, draft: { id, title, kind, createdAt, updatedAt: now.toISOString(), sections } };
}

/** Reads the stored drafts, dropping any that no longer validate. Newest first. */
export function readCaseDrafts(masterResult: unknown): CaseDraft[] {
  const raw = asRecord(masterResult).drafts;
  if (!Array.isArray(raw)) return [];
  const drafts: CaseDraft[] = [];
  for (const entry of raw) {
    const checked = validateDraft(entry, new Date(0));
    if (checked.ok) {
      const updatedAt = typeof asRecord(entry).updatedAt === "string" ? (asRecord(entry).updatedAt as string) : checked.draft.updatedAt;
      drafts.push({ ...checked.draft, updatedAt });
    }
  }
  return drafts.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
}

export function upsertDraft(drafts: CaseDraft[], draft: CaseDraft): { ok: true; drafts: CaseDraft[] } | { ok: false; error: string } {
  const others = drafts.filter((existing) => existing.id !== draft.id);
  if (others.length >= MAX_DRAFTS) return { ok: false, error: `A case can hold up to ${MAX_DRAFTS} drafts. Delete one first.` };
  return { ok: true, drafts: [draft, ...others] };
}

// ---------------------------------------------------------------------------
// Starting points. Every line comes from the user's own record.
// ---------------------------------------------------------------------------

const section = (heading: string, body: string): DraftSection => ({
  id: newId("part"),
  heading,
  text: body,
  reviewed: false,
});

function draftShell(title: string, kind: DraftKind, sections: DraftSection[], now: Date): CaseDraft {
  const stamp = now.toISOString();
  return { id: newId("draft"), title, kind, createdAt: stamp, updatedAt: stamp, sections };
}

export function blankDraft(now: Date): CaseDraft {
  return draftShell("Untitled draft", "blank", [section("", "")], now);
}

export type TimelineEntry = {
  /** ISO date the user picked, if any. */
  date: string | null;
  /** The user's own words for when, if no exact date. */
  when: string | null;
  title: string;
  detail: string | null;
  source: "timeline" | "document";
};

function formatEntryDate(entry: TimelineEntry): string {
  if (entry.date) {
    const [year, month, day] = entry.date.split("-").map(Number);
    if (year && month && day) {
      return new Date(Date.UTC(year, month - 1, day)).toLocaleDateString("en-CA", {
        year: "numeric",
        month: "long",
        day: "numeric",
        timeZone: "UTC",
      });
    }
  }
  return entry.when ? `${entry.when} (approximate)` : "Date not recorded";
}

/** Dated entries in order, then the undated ones, each kept as the user recorded it. */
export function orderTimeline(entries: TimelineEntry[]): TimelineEntry[] {
  const dated = entries.filter((entry) => entry.date).sort((a, b) => (a.date as string).localeCompare(b.date as string));
  return [...dated, ...entries.filter((entry) => !entry.date)];
}

export function chronologyDraft(entries: TimelineEntry[], now: Date): CaseDraft {
  const ordered = orderTimeline(entries);
  const sections = ordered.length
    ? ordered.map((entry) =>
        section(formatEntryDate(entry), [entry.title, entry.detail].filter(Boolean).join("\n\n")),
      )
    : [section("", "Nothing is recorded on your timeline yet. Add events on the Timeline tab, or write them here.")];
  return draftShell("Chronology", "chronology", sections, now);
}

/**
 * An outline only: one numbered statement per recorded event, in the order
 * they happened, for the user to rewrite in their own words. It states no rule
 * about affidavits (that would need a source) and adds no fact.
 */
export function affidavitOutlineDraft(entries: TimelineEntry[], now: Date): CaseDraft {
  const ordered = orderTimeline(entries);
  const statements = ordered.map((entry, index) =>
    `${index + 1}. ${formatEntryDate(entry)}: ${entry.title}${entry.detail ? ` ${entry.detail}` : ""}`,
  );
  return draftShell(
    "Affidavit outline",
    "affidavit-outline",
    [
      section("About you", ""),
      section(
        "What happened",
        statements.length
          ? statements.join("\n")
          : "Nothing is recorded on your timeline yet. Write what happened as numbered statements, one fact each.",
      ),
      section("Documents you refer to", ""),
    ],
    now,
  );
}

export type IntakeStory = {
  facts?: string;
  goal?: string;
  yourName?: string;
  otherParty?: string;
  timeline?: string;
  evidence?: string;
};

export function yourStoryDraft(intake: IntakeStory, now: Date): CaseDraft {
  const parts: DraftSection[] = [];
  const people = [intake.yourName?.trim() && `You: ${intake.yourName.trim()}`, intake.otherParty?.trim() && `The other side: ${intake.otherParty.trim()}`]
    .filter(Boolean)
    .join("\n");
  if (people) parts.push(section("Who is involved", people));
  parts.push(section("What happened", intake.facts?.trim() || ""));
  if (intake.timeline?.trim()) parts.push(section("When things happened", intake.timeline.trim()));
  if (intake.evidence?.trim()) parts.push(section("What you have to show it", intake.evidence.trim()));
  parts.push(section("What you want", intake.goal?.trim() || ""));
  return draftShell("Your story", "your-story", parts, now);
}

/** A draft from the old browser-only drafting page, kept as the user left it. */
export function importLegacyWorkspaceDocument(raw: unknown, now: Date): CaseDraft | null {
  const doc = asRecord(raw);
  if (!Array.isArray(doc.sections)) return null;
  const sections = (doc.sections as unknown[])
    .map((entry) => {
      const legacy = asRecord(entry);
      const paragraphs = Array.isArray(legacy.paragraphs) ? legacy.paragraphs.filter((item): item is string => typeof item === "string") : [];
      const bullets = Array.isArray(legacy.bulletPoints) ? legacy.bulletPoints.filter((item): item is string => typeof item === "string") : [];
      const body = [...paragraphs, ...bullets.map((item) => `• ${item}`)].join("\n\n").slice(0, MAX_SECTION_TEXT);
      return section(typeof legacy.heading === "string" ? legacy.heading.slice(0, MAX_HEADING_LENGTH) : "", body);
    })
    .slice(0, MAX_SECTIONS);
  if (sections.length === 0) return null;
  const title = typeof doc.title === "string" && doc.title.trim() ? doc.title.trim().slice(0, MAX_TITLE_LENGTH) : "Imported draft";
  return draftShell(title, "imported", sections, now);
}

/** Plain text, for copying or a .txt download. */
export function draftAsPlainText(draft: CaseDraft): string {
  return [
    draft.title,
    "",
    ...draft.sections.flatMap((part) => [...(part.heading ? [part.heading.toUpperCase()] : []), part.text, ""]),
  ].join("\n").trim() + "\n";
}

const escapeHtml = (value: string) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/**
 * A Word-readable document. Word opens HTML saved with a .doc extension, so
 * this needs no library (the build cannot add one) and keeps headings and
 * paragraphs as real headings and paragraphs the user can edit there.
 */
export function draftAsWordHtml(draft: CaseDraft): string {
  const body = draft.sections
    .map((part) => {
      const heading = part.heading ? `<h2>${escapeHtml(part.heading)}</h2>` : "";
      const paragraphs = part.text
        .split(/\n{2,}/)
        .map((paragraph) => `<p>${escapeHtml(paragraph).replace(/\n/g, "<br>")}</p>`)
        .join("");
      return heading + paragraphs;
    })
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(draft.title)}</title>` +
    `<style>body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.5}h1{font-size:16pt}h2{font-size:13pt;margin-top:18pt}</style>` +
    `</head><body><h1>${escapeHtml(draft.title)}</h1>${body}</body></html>`;
}
