/**
 * The two fixed messages a user sees when the safety pass classifies their
 * story as immediate danger or as distress.
 *
 * *** WHY THESE MOVED OUT OF safetyPass.ts ***
 *
 * They needed to be in the review packet — they are the highest-consequence
 * strings in the product, `safetyPass.ts`'s own header says they need clinical
 * review before shipping, and neither was indexed.
 *
 * The first attempt simply imported them into `contentInventory.ts`. That
 * broke the production build, and the break was informative:
 * `safetyPass.ts` imports `openaiClient`, which imports `aiCallLog`, which
 * imports `node:async_hooks`. `contentInventory` is read by `outputGuard`,
 * which is read by `HomeLocationGate` — a client component. So indexing the
 * content pulled a Node-only API into the browser bundle.
 *
 * Content does not belong in a module that makes network calls. Moving it here
 * is the fix, and the build failure is what named it: this file imports
 * nothing.
 *
 * *** NOTHING ABOUT THE WORDING CHANGED IN THE MOVE ***
 *
 * Byte-for-byte what `safetyPass.ts` held, sourcing comments included, which is
 * a property asserted by `verifyInventoryCoverage`. `safetyPass.ts` re-exports
 * both names so every existing importer is untouched.
 *
 * *** WHAT IS SOURCED AND WHAT IS NOT ***
 *
 * The phone numbers below are individually fetched from ontario.ca and quoted
 * verbatim; the comment records each one. What has NEVER been reviewed is the
 * message: whether this is the right thing to say to someone who has just
 * disclosed danger, in this order, at this length. That is a clinical
 * judgment, not a sourcing one, and it is what the review packet now routes to
 * the right person.
 */

// *** Numbers below are real and directly sourced (Session 8) -- the
// MESSAGE AS A WHOLE STILL NEEDS REAL REVIEW. See file header. ***
//
// Sources, each directly fetched and quoted, not taken from a search
// summary or recalled from training data:
// - Assaulted Women's Helpline (1-866-863-0511, 416-863-0511) and
//   Fem'aide (1-877-336-2433): ontario.ca/page/connect-supports-survivors-violence,
//   quoted verbatim as "Toll-free: 1-866-863-0511" / "416-863-0511" /
//   "Toll-free: 1-877-336-2433".
// - ConnexOntario (1-866-531-2600): ontario.ca/page/find-mental-health-support,
//   quoted verbatim as "Toll-free: 1-866-531-2600".
// - Child protection: no single province-wide number exists on any page
//   checked. ontario.ca/page/report-child-abuse-and-neglect says, quoted
//   verbatim: "Report it to a children's aid society or, if someone is in
//   immediate danger, call the police" -- directing people to their LOCAL
//   society, not a central number. Stated that way below rather than
//   inventing a number that doesn't exist.
// - A general/national crisis line (988-style) remains unresolved -- see
//   file header. Not included below because it was not found, not because
//   it was overlooked.
export const IMMEDIATE_DANGER_MESSAGE =
  "If you are in immediate danger, please call 911.\n\n" +
  "CourtSimplified is a legal information platform. It is not equipped to respond to emergencies " +
  "or provide crisis support, and this intake cannot continue right now.\n\n" +
  "Other support that may help:\n" +
  "- Assaulted Women's Helpline: 1-866-863-0511 (toll-free), or 416-863-0511\n" +
  "- Fem'aide (French-language support): 1-877-336-2433 (toll-free)\n" +
  "- ConnexOntario mental health, addictions, and problem gambling helpline: 1-866-531-2600 (toll-free)\n" +
  "- To report a child who may be in need of protection: contact your local Children's Aid Society, " +
  "or call police if a child is in immediate danger. There is no single province-wide number for " +
  "this -- Ontario's own guidance directs people to their local society.";

// Fixed, short, warm -- not generated by the model. Doesn't characterize
// the legal situation or give advice; just acknowledges and signals the
// flow will continue without rushing. The "slower pace" itself isn't
// built this session -- see the file header.
export const DISTRESS_ACKNOWLEDGMENT =
  "Thank you for sharing that -- it sounds like a genuinely difficult situation. We'll take this " +
  "at a slower pace, and there's no need to rush through anything.";

