param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputFolder
)

$inventoryPath = Join-Path $OutputFolder "MASTER_PROJECT_INVENTORY.md"

$content = @"
# CourtSimplified – Master Project Inventory

Generated:
$(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Project Root:
$ProjectRoot

---

## Project Purpose

CourtSimplified is a Litigation Operating System designed to assist self-represented litigants through every stage of litigation.

The project combines:

- Legal procedure
- Evidence management
- AI reasoning
- Litigation intelligence
- Workflow management
- Court document generation
- Authority verification

---

## Engineering Principles

- Documentation is the primary source of truth.
- Avoid duplicate engines.
- Avoid parallel workflows.
- Extend existing architecture whenever practical.
- Keep engineering documentation synchronized with the codebase.

---

## Documentation

This inventory is automatically generated by the Engineering Snapshot system.

Generated by:
Generate-ProjectInventory.ps1
"@

$content | Set-Content $inventoryPath -Encoding UTF8

Write-Host "Generated MASTER_PROJECT_INVENTORY.md"