/**
 * Exports every piece of legal or procedural content to a review packet.
 *
 *   npm run content:export
 *
 * Writes docs/review-packet.csv (for the reviewer to fill in and return) and
 * docs/review-packet.md (readable, for reading rather than editing).
 *
 * COSTS NOTHING. Pure reads of the content registries. No model call.
 *
 * *** THIS IS THE ARTEFACT WE HAND A LICENSEE ***
 *
 * The LSO A2I policy allows AI to select from human-reviewed content. Nothing
 * in this product has been reviewed by a licensed Ontario lawyer or paralegal
 * yet, and the single largest piece of work before compliance is getting that
 * review done. This script makes the ask concrete: here is every item, its
 * exact current wording, its official source, and where a user encounters it.
 *
 * The CSV comes back with `reviewedBy` and `reviewedAt` filled in and is fed to
 * `scripts/content/importReviewResults.ts`, so review outcomes land in the repo
 * without anyone hand-editing a TypeScript catalogue.
 */

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { collectContentInventory } from "../../src/lib/content-library/contentInventory";
import {
  approvalFor,
  approvalSummary,
  type ContentItem,
} from "../../src/lib/content-library/licenseeReview";

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const CSV_PATH = path.join(REPO_ROOT, "docs", "review-packet.csv");
const MD_PATH = path.join(REPO_ROOT, "docs", "review-packet.md");

/** RFC 4180 quoting: wrap in quotes, double any embedded quote. */
function csvCell(value: string): string {
  return `"${String(value).replace(/"/g, '""')}"`;
}

function isPlaceholder(item: ContentItem): boolean {
  return item.text.includes("[NEEDS LICENSEE REVIEW:");
}

function writeCsv(items: ContentItem[]): void {
  const header = [
    "id",
    "type",
    "pathway",
    "stage",
    "current_text",
    "source_url",
    "appears_in",
    "version",
    "status",
    "reviewed_by",
    "reviewed_at",
    "reviewer_note",
  ];

  const rows = items.map((entry) => {
    const approval = approvalFor(entry.id);
    const current = approval && approval.version === entry.version;
    return [
      entry.id,
      entry.type,
      entry.pathway,
      entry.stage,
      entry.text,
      entry.sourceUrl,
      entry.appearsIn,
      String(entry.version),
      current ? "approved" : approval ? "approval-stale" : "draft",
      approval?.reviewedBy ?? "",
      approval?.reviewedAt ?? "",
      approval?.note ?? "",
    ].map(csvCell).join(",");
  });

  fs.writeFileSync(CSV_PATH, [header.map(csvCell).join(","), ...rows].join("\n") + "\n", "utf8");
}

function writeMarkdown(items: ContentItem[]): void {
  const summary = approvalSummary(items);
  const placeholders = items.filter(isPlaceholder);
  const byType = new Map<string, ContentItem[]>();
  for (const entry of items) {
    byType.set(entry.type, [...(byType.get(entry.type) ?? []), entry]);
  }

  const lines: string[] = [
    "# Content review packet",
    "",
    `Generated by \`npm run content:export\` on ${new Date().toISOString().slice(0, 10)}. Not hand-edited.`,
    "",
    "## What this is, and what we are asking for",
    "",
    "Every piece of legal or procedural text CourtSimplified shows a user, with its",
    "exact current wording, its official source, and where it appears in the product.",
    "",
    "We are asking a licensed Ontario lawyer or paralegal to read each item and say",
    "whether it is accurate and appropriate to show to a self-represented person.",
    "",
    "**Nothing in this product has been reviewed by a licensee yet.** Some items are",
    "marked `reviewed` in the codebase — that records an internal editorial pass by a",
    "developer, not professional review, and the two are tracked separately so they",
    "cannot be confused.",
    "",
    "## How to return it",
    "",
    "Fill in `reviewed_by` (name and LSO number), `reviewed_at` (YYYY-MM-DD) and",
    "optionally `reviewer_note` in `docs/review-packet.csv`, then run:",
    "",
    "```",
    "npm run content:import -- --file docs/review-packet.csv",
    "```",
    "",
    "An approval is recorded against the item's current `version`. If the wording is",
    "edited afterwards the approval no longer applies, and the item returns to draft.",
    "",
    "## Summary",
    "",
    `| Measure | Count |`,
    `|---|---|`,
    `| Total items | ${summary.total} |`,
    `| Approved (current version) | ${summary.approved} |`,
    `| Draft / unreviewed | ${summary.draft} |`,
    `| Approvals voided by later edits | ${summary.staleApprovals} |`,
    `| Items that are unwritten placeholders | ${placeholders.length} |`,
    "",
  ];

  if (placeholders.length > 0) {
    lines.push(
      "## Placeholders — text that does not exist yet",
      "",
      "These are not awaiting approval; they are awaiting **writing**. Each says what",
      "is needed. They exist because the alternative was inventing legal content,",
      "which is the thing this work exists to prevent.",
      "",
    );
    for (const entry of placeholders) {
      lines.push(`- **${entry.id}** (${entry.pathway} / ${entry.stage}) — ${entry.text}`);
    }
    lines.push("");
  }

  for (const [type, entries] of [...byType.entries()].sort()) {
    lines.push(`## ${type} (${entries.length})`, "");
    for (const entry of entries) {
      const approval = approvalFor(entry.id);
      const status = approval && approval.version === entry.version ? "approved" : "draft";
      lines.push(
        `### \`${entry.id}\``,
        "",
        `- **Status:** ${status}${approval ? ` — ${approval.reviewedBy}, ${approval.reviewedAt}` : ""}`,
        `- **Pathway / stage:** ${entry.pathway} / ${entry.stage}`,
        `- **Appears in:** ${entry.appearsIn}`,
        `- **Source:** ${entry.sourceUrl || "_none recorded_"}`,
        "",
        "```",
        entry.text,
        "```",
        "",
      );

      /*
       * *** THE QUESTION AUTOMATED VERIFICATION CANNOT ASK ***
       *
       * Printed against every stage answer, because this is the check that
       * caught the worst error in the product and the only one a person can
       * make.
       *
       * An independent review found a block on the PLAINTIFF's
       * defence-period-expired stage telling the reader to file a Defence
       * (Form 9A). Every sentence was a true statement about a defendant,
       * every quote was real, and every automated gate passed it — because no
       * individual sentence was false. Sentence-level verification is blind to
       * who the reader is.
       *
       * Only on stage answers: asking it of an intake question or a form
       * description would be noise, and a prompt that appears everywhere gets
       * read nowhere.
       */
      if (entry.type === "stage-answer") {
        lines.push(
          "> **Read this as the person at this stage.** Does every instruction apply to",
          "> you, and could you follow it? Check whose step it is (a plaintiff asks the",
          "> clerk to note a defendant in default with Form 9B; a defendant files the",
          "> Defence, Form 9A), whether it speaks _to_ you or _about_ you, and who served",
          "> whom. If it has those the wrong way round, nothing else about it matters.",
          "",
        );
      }
    }
  }

  fs.writeFileSync(MD_PATH, lines.join("\n") + "\n", "utf8");
}

function main(): void {
  const items = collectContentInventory();

  /*
   * DUPLICATE IDS ARE REPORTED, NOT SILENTLY TOLERATED.
   *
   * An approval is keyed by id, so two items sharing one id means an approval
   * cannot be attached to a specific piece of text. This surfaced a real
   * pre-existing defect on first run: DEPTH_QUESTIONS contains
   * `depth-contractor-loss` TWICE, with the same elementId and different
   * question text, so which one a user is asked depends on lookup order.
   * `verifyDepthQuestions.ts` does not check id uniqueness.
   *
   * The export still runs — blocking the whole packet on a content bug helps
   * nobody — but duplicates are listed, suffixed so each row is addressable,
   * and the exit code is non-zero so this cannot pass unnoticed in CI.
   */
  const seen = new Map<string, number>();
  const duplicateIds: string[] = [];

  for (const entry of items) {
    const count = seen.get(entry.id) ?? 0;
    seen.set(entry.id, count + 1);
    if (count > 0) {
      duplicateIds.push(entry.id);
      entry.id = `${entry.id}#${count + 1}`;
    }
  }

  fs.mkdirSync(path.dirname(CSV_PATH), { recursive: true });
  writeCsv(items);
  writeMarkdown(items);

  const summary = approvalSummary(items);
  const placeholders = items.filter(isPlaceholder).length;

  console.log(`items:        ${summary.total}`);
  console.log(`approved:     ${summary.approved}`);
  console.log(`draft:        ${summary.draft}`);
  console.log(`placeholders: ${placeholders}`);
  console.log(`\nwrote docs/review-packet.csv and docs/review-packet.md`);

  if (duplicateIds.length > 0) {
    console.log(
      `\nDUPLICATE CONTENT IDS (${duplicateIds.length}) — a real defect, suffixed here so the packet stays usable:`,
    );
    for (const id of duplicateIds) console.log(`  ${id}`);
    console.log("  Two items sharing an id cannot each carry their own approval.");
    process.exitCode = 1;
  }
}

const isDirect = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;
if (isDirect) main();
