/**
 * Minimal safety/distress pass -- seed of phase 1 in docs/AI_INTAKE_DESIGN.md
 * ("Safety pass (AI): distress/danger/out-of-scope detection, runs first,
 * can halt intake"). Session 4: detection and a fixed acknowledgment/
 * redirect only -- no UI, no "slower pace" mechanism, no live route. This
 * is the gap flagged at the end of Session 3: no free-text story should
 * reach extractIntakeFacts.ts without running through here first.
 *
 * Same shape as extractIntakeFacts.ts: one OpenAI call, gpt-4o-mini,
 * temperature 0. The model's job is classification ONLY -- it never gives
 * advice, never characterizes the legal situation, and never writes the
 * text a user in danger or distress actually sees. That text is a fixed,
 * reviewed constant below (same "fixed skeleton, no AI on safety-critical
 * wording" principle as questionBank.ts's question text, applied to
 * content where the cost of the model improvising is much higher).
 *
 * Session 5 adversarially tested this against 8 hard cases (see
 * scripts/verification/verifySafetyPassRegression.ts, which now holds all
 * 11 cases from Sessions 4-5 permanently) and found two real problems,
 * both from the same root cause: "immediate-danger" was triggering on
 * violent-adjacent CONTENT (a mention of past violence, a disclaimed
 * hyperbolic phrase) rather than requiring an explicit, current statement
 * of danger. Session 6 narrows the immediate-danger criteria to fix this
 * -- distress/clear were left untouched (Session 5 found no failures
 * there on their own terms; the two misses were danger-detection
 * over-triggering, not a distress/clear boundary problem).
 *
 * *** NEEDS REAL REVIEW BEFORE THIS EVER SHIPS ***
 * IMMEDIATE_DANGER_MESSAGE below is NOT sourced or clinically/legally
 * reviewed. CLAUDE.md's three-domain sourcing rule governs legal facts;
 * crisis-resource content (which specific helpline, which phone number,
 * regional availability, hours of operation) is a different, equally
 * serious category this session has no verified source for and no
 * mandate to invent one. Per this session's own instructions: a
 * clearly-marked placeholder, not a guessed phone number, is what belongs
 * here until someone with the right expertise reviews and confirms it.
 * "911" is kept as the one specific fact in this message because it's
 * Canada's universal emergency number, not a specialized resource lookup.
 */

import OpenAI from "openai";

export type SafetyClassification = "immediate-danger" | "distress" | "clear";

export type SafetyPassResult = {
  classification: SafetyClassification;
  /** One short sentence, for internal logging only -- never shown raw to the user. */
  reason?: string;
  /** Fixed, reviewed text for immediate-danger/distress. Undefined for "clear". */
  userMessage?: string;
};

// *** PLACEHOLDER -- NOT REVIEWED. See file header. ***
// Needs: a verified, current Canada/Ontario-specific crisis line (and
// possibly a domestic-violence-specific and/or child-protection-specific
// line), confirmed correct by someone qualified to confirm it, before any
// version of this text reaches a real user.
export const IMMEDIATE_DANGER_MESSAGE =
  "If you are in immediate danger, please call 911.\n\n" +
  "CourtSimplified is a legal information platform. It is not equipped to respond to emergencies " +
  "or provide crisis support, and this intake cannot continue right now.\n\n" +
  "[PLACEHOLDER -- NEEDS REAL REVIEW: verified Canada/Ontario crisis resources belong here -- for " +
  "example a national crisis line, a domestic violence helpline, and/or a child protection " +
  "reporting line, each confirmed current and correct before this ships.]";

// Fixed, short, warm -- not generated by the model. Doesn't characterize
// the legal situation or give advice; just acknowledges and signals the
// flow will continue without rushing. The "slower pace" itself isn't
// built this session -- see the file header.
export const DISTRESS_ACKNOWLEDGMENT =
  "Thank you for sharing that -- it sounds like a genuinely difficult situation. We'll take this " +
  "at a slower pace, and there's no need to rush through anything.";

const SYSTEM_PROMPT = `You are a safety classifier for a legal self-help intake form. Read the free-text story and classify it into exactly one category. You do not give advice, you do not characterize the legal or factual situation, and you do not decide what happens next -- you only classify.

Categories:

- "immediate-danger": ONLY when the person explicitly and unambiguously states, in their own words, that they are CURRENTLY unsafe or being threatened -- a threat, act of violence, or fear for physical safety that is happening now, was very recent and remains unresolved, or a child currently at risk. This must be a direct statement, not something inferred from violent word choice, a scary topic, or emotional tone. Do NOT classify as immediate-danger:
  - Violence described as being in the past, with nothing indicating it's ongoing or unresolved. Example: "he was physically violent with me during our relationship, including choking me once; I moved out months ago and we're no longer in contact" -- this describes something serious, but there is no current threat. Classify this as "distress" instead, given the seriousness of what's being recounted.
  - Hyperbolic or figurative violent language the person themselves signals isn't a real threat. Example: "I could kill him, not seriously, obviously, I'm just so fed up" -- this is ordinary frustrated speech, not a threat. Classify this as "clear".
  - A violent or frightening topic mentioned without the person saying THEY are currently unsafe.
  DO classify as immediate-danger when the person directly describes a real, explicit threat or act of violence that is current or very recent and unresolved -- even if it's mentioned briefly within an otherwise ordinary story. Example: someone recounting an unrelated contract dispute who also mentions the other party showed up recently and threatened them, leaving them scared -- that threat is real, explicit, and unresolved, so this IS immediate-danger, regardless of how much of the story is about something else.

- "distress": no immediate danger (per the strict test above), but the story contains heavy content well beyond an ordinary factual account -- either strong emotional language (despair, being overwhelmed, crying, hopelessness) or serious-but-not-current content like past violence or trauma recounted as background, even when the person's tone is calm or flat.

- "clear": an ordinary factual account, proceed normally. This includes anger or frustration on its own (without despair or hopelessness), and hyperbolic language the speaker themselves disclaims as not serious.

Return a JSON object: {"classification": "immediate-danger" | "distress" | "clear", "reason": "<one short sentence for internal logging only, never shown to any user>"}. Omit "reason" (empty string) when classification is "clear".`;

function isValidClassification(value: unknown): value is SafetyClassification {
  return value === "immediate-danger" || value === "distress" || value === "clear";
}

/**
 * One OpenAI call: free text -> SafetyClassification + a fixed, reviewed
 * userMessage (never model-generated). Must run before
 * extractIntakeFacts.ts on any free-text story.
 */
export async function runSafetyPass(storyText: string, apiKey: string): Promise<SafetyPassResult> {
  const client = new OpenAI({ apiKey });
  const response = await client.chat.completions.create({
    model: "gpt-4o-mini",
    temperature: 0,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: storyText },
    ],
  });

  const content = response.choices[0]?.message?.content ?? "{}";
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    parsed = {};
  }

  const record = parsed && typeof parsed === "object" ? (parsed as Record<string, unknown>) : {};
  const classification: SafetyClassification = isValidClassification(record.classification)
    ? record.classification
    // Fail closed: an unparseable/unexpected model response is treated as
    // distress, not "clear" -- a false pause costs a slower start; a false
    // "clear" could mean skipping safety content when it was needed.
    : "distress";
  const reason = typeof record.reason === "string" && record.reason.trim() ? record.reason.trim() : undefined;

  if (classification === "immediate-danger") {
    return { classification, reason, userMessage: IMMEDIATE_DANGER_MESSAGE };
  }
  if (classification === "distress") {
    return { classification, reason, userMessage: DISTRESS_ACKNOWLEDGMENT };
  }
  return { classification: "clear" };
}
