import {
  AuthorityRegistryModel,
  VerifiedAuthorityEntry,
} from "./authorityRegistryArchitecture";

const NOW = "2026-06-30T00:00:00.000Z";

export const VERIFIED_AUTHORITY_SEED_ENTRIES: VerifiedAuthorityEntry[] = [
  {
    id: "authority_defamation_grant_v_torstar_2009_scc_61",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Grant v. Torstar Corp.",
    shortTitle: "Grant",
    citation: "Grant v. Torstar Corp., 2009 SCC 61",
    neutralCitation: "2009 SCC 61",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 2009,
    bindingWeight: "binding",
    importanceScore: 98,
    confidence: "high",
    courtPaths: ["civil", "small-claims"],
    legalDomains: ["defamation"],
    proceduralStages: ["pre-litigation", "starting-case", "responding", "motion", "trial"],
    topicTags: ["defamation", "responsible communication", "public interest"],
    doctrineTags: ["defamation-defence", "responsible-communication"],
    ruleReferences: [],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Recognizes responsible communication on matters of public interest as a defence in defamation.",
    plainLanguageSummary:
      "This case matters when someone published something about another person and says it was responsibly communicated on a matter of public interest.",
    legalTestSummary:
      "The analysis focuses on public interest and whether the publication was responsible in light of the circumstances.",
    howCourtsUseIt: [
      "To assess responsible communication defences.",
      "To separate public-interest reporting from unsupported reputational harm.",
    ],
    practicalUse: [
      "Ask what was said, who received it, why it was shared, and what steps were taken to verify it.",
    ],
    commonMistakes: [
      "Assuming every public comment is protected.",
      "Ignoring whether factual assertions were verified.",
    ],
    limitsAndWarnings: [
      "Context and exact words matter.",
      "This should not be treated as a complete defamation analysis by itself.",
    ],
    legalTestElements: [
      {
        id: "grant_public_interest",
        label: "Public interest",
        explanation: "The subject matter must be one the public has a genuine interest in knowing about.",
        proofNeeded: ["Publication context", "Audience", "Subject matter"],
        commonWeaknesses: ["Private dispute presented as public interest"],
        evidenceExamples: ["Article", "post", "email", "distribution context"],
        burdenRelevance: "Usually raised by the defendant as a defence.",
      },
      {
        id: "grant_responsibility",
        label: "Responsible communication",
        explanation: "The court considers whether reasonable steps were taken before publication.",
        proofNeeded: ["Verification steps", "Source reliability", "Opportunity to respond"],
        commonWeaknesses: ["No verification", "Reckless repetition"],
        evidenceExamples: ["Messages", "notes", "source records"],
        burdenRelevance: "Defendant must support the defence.",
      },
    ],
    evidenceImplications: [
      {
        id: "grant_evidence_publication_context",
        label: "Publication context",
        explanation: "The context affects public interest, responsibility, malice, and harm.",
        evidenceUsuallyNeeded: ["Exact words", "recipient/audience", "date", "platform"],
        weakEvidenceWarnings: ["Paraphrased allegations without screenshot or record"],
        strongEvidenceExamples: ["Full screenshot", "email headers", "witness recipient"],
      },
    ],
    workflowLinks: [
      { route: "/builder", reason: "Clarify exact words and audience." },
      { route: "/evidence", reason: "Preserve publication proof." },
      { route: "/litigation-strategy", reason: "Assess defences and response strategy." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: ["authority_defamation_bent_v_platnick_2020_scc_23"],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: ["authority_defamation_wic_radio_v_simpson_2008_scc_40"],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not say a defence applies without the exact publication and context."],
    },
    suggestedAiQuestions: [
      "What exact words were published?",
      "Who received or saw the statement?",
      "Was the statement about you specifically?",
    ],
    suggestedEvidenceQuestions: [
      "Do you have the full message, post, email, or screenshot?",
      "Can you prove who received it?",
    ],
    suggestedWorkflowActions: [
      "Preserve the publication record.",
      "Identify possible defences before drafting.",
    ],
    sourceReferences: [
      {
        id: "src_grant_canlii",
        sourceType: "canlii",
        title: "Grant v. Torstar Corp.",
        citationOrUrlLabel: "2009 SCC 61",
        notes: ["Verified starter authority."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_charter_oakes_1986_scc",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "R. v. Oakes",
    shortTitle: "Oakes",
    citation: "R. v. Oakes, [1986] 1 S.C.R. 103",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 1986,
    bindingWeight: "binding",
    importanceScore: 100,
    confidence: "high",
    courtPaths: ["civil", "criminal-related"],
    legalDomains: ["civil-charter"],
    proceduralStages: ["motion", "trial", "appeal"],
    topicTags: ["Charter", "section 1", "proportionality"],
    doctrineTags: ["oakes-test", "justification"],
    ruleReferences: [],
    statuteReferences: ["Canadian Charter of Rights and Freedoms, s. 1"],
    formReferences: [],
    corePrinciple:
      "Creates the section 1 proportionality framework for justifying Charter limits.",
    plainLanguageSummary:
      "If a Charter right is limited, this case helps assess whether the government can justify the limit.",
    legalTestSummary:
      "Pressing and substantial objective, rational connection, minimal impairment, and proportionality.",
    howCourtsUseIt: [
      "To analyze whether a Charter breach can be justified.",
      "To structure constitutional arguments.",
    ],
    practicalUse: [
      "Use only when there is state action and a Charter right is engaged.",
    ],
    commonMistakes: [
      "Using Oakes where there is no government action.",
      "Skipping evidence about the objective and proportionality.",
    ],
    limitsAndWarnings: [
      "Charter analysis is complex and usually needs careful human review.",
    ],
    legalTestElements: [
      {
        id: "oakes_rational_connection",
        label: "Rational connection",
        explanation: "The limit must be logically connected to the government objective.",
        proofNeeded: ["Government objective", "Connection between law/action and objective"],
        commonWeaknesses: ["Objective stated too generally"],
        evidenceExamples: ["Legislation", "policy record", "decision record"],
        burdenRelevance: "Government usually bears justification burden under s. 1.",
      },
    ],
    evidenceImplications: [
      {
        id: "oakes_state_record",
        label: "State action record",
        explanation: "The record matters because Charter claims depend on state conduct.",
        evidenceUsuallyNeeded: ["Decision", "policy", "order", "record", "transcript"],
        weakEvidenceWarnings: ["No government actor identified"],
        strongEvidenceExamples: ["Official decision letter", "court order", "transcript"],
      },
    ],
    workflowLinks: [
      { route: "/builder", reason: "Identify government actor and right affected." },
      { route: "/evidence", reason: "Collect decision and record." },
      { route: "/litigation-strategy", reason: "Assess Charter theory and remedy." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: ["authority_charter_bedford_2013_scc_72", "authority_charter_carter_2015_scc_5"],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not apply Charter analysis to purely private disputes."],
    },
    suggestedAiQuestions: [
      "What government actor or court decision are you challenging?",
      "Which Charter right do you think was affected?",
    ],
    suggestedEvidenceQuestions: [
      "Do you have the order, decision, transcript, or policy?",
    ],
    suggestedWorkflowActions: ["Screen Charter issue.", "Preserve the record."],
    sourceReferences: [
      {
        id: "src_oakes_scc",
        sourceType: "scc",
        title: "R. v. Oakes",
        citationOrUrlLabel: "[1986] 1 S.C.R. 103",
        notes: ["Verified SCC source."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_civil_procedure_hryniak_2014_scc_7",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Hryniak v. Mauldin",
    shortTitle: "Hryniak",
    citation: "Hryniak v. Mauldin, 2014 SCC 7",
    neutralCitation: "2014 SCC 7",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 2014,
    bindingWeight: "binding",
    importanceScore: 95,
    confidence: "high",
    courtPaths: ["civil", "small-claims"],
    legalDomains: ["procedural"],
    proceduralStages: ["motion", "trial"],
    topicTags: ["summary judgment", "proportionality", "access to justice"],
    doctrineTags: ["culture-shift", "summary-judgment"],
    ruleReferences: ["Ontario Rules of Civil Procedure, Rule 20"],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Summary judgment can be used where it provides a fair, just, proportionate, and timely process.",
    plainLanguageSummary:
      "This case matters when a party asks the court to decide a case or issue without a full trial.",
    legalTestSummary:
      "The court asks whether there is a genuine issue requiring trial and whether summary judgment can fairly resolve the dispute.",
    howCourtsUseIt: [
      "To assess summary judgment motions.",
      "To apply proportionality and access-to-justice reasoning.",
    ],
    practicalUse: [
      "Consider whether the record is strong enough for a motion or whether more evidence is needed.",
    ],
    commonMistakes: [
      "Assuming summary judgment is simple.",
      "Bringing the motion without a complete evidence record.",
    ],
    limitsAndWarnings: [
      "Rule-specific requirements still matter.",
      "Court path and procedural stage must be confirmed.",
    ],
    legalTestElements: [
      {
        id: "hryniak_genuine_issue",
        label: "Genuine issue requiring trial",
        explanation: "The court assesses whether a trial is needed to fairly decide the dispute.",
        proofNeeded: ["Affidavit evidence", "documents", "record showing facts are sufficiently clear"],
        commonWeaknesses: ["Conflicting evidence needing credibility findings"],
        evidenceExamples: ["Affidavits", "contracts", "emails", "transcripts"],
        burdenRelevance: "Moving party must support the motion record.",
      },
    ],
    evidenceImplications: [
      {
        id: "hryniak_motion_record",
        label: "Motion record",
        explanation: "The strength of the motion depends on the completeness of the record.",
        evidenceUsuallyNeeded: ["Affidavits", "exhibits", "key documents"],
        weakEvidenceWarnings: ["Unsupported allegations"],
        strongEvidenceExamples: ["Clear documents and admissions"],
      },
    ],
    workflowLinks: [
      { route: "/case-dashboard", reason: "Confirm stage and procedural status." },
      { route: "/evidence", reason: "Build motion-ready evidence." },
      { route: "/court-package", reason: "Prepare motion package only after readiness review." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: [],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: [],
    },
    annualPracticeLinks: [
      {
        rule: "Rule 20",
        sectionLabel: "Summary Judgment",
        commentarySummary:
          "Annual Practice commentary should be added from verified user-provided extraction.",
        notes: ["Pending Annual Practice extraction."],
      },
    ],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not recommend summary judgment without procedural and evidence review."],
    },
    suggestedAiQuestions: [
      "Is there already a court case started?",
      "What facts are disputed?",
      "Do you have affidavit evidence or documents proving the key facts?",
    ],
    suggestedEvidenceQuestions: [
      "What documents prove the issue without needing live testimony?",
    ],
    suggestedWorkflowActions: ["Review Rule 20 readiness.", "Check evidence completeness."],
    sourceReferences: [
      {
        id: "src_hryniak_scc",
        sourceType: "scc",
        title: "Hryniak v. Mauldin",
        citationOrUrlLabel: "2014 SCC 7",
        notes: ["Verified SCC/CanLII authority."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_negligence_saadati_2017_scc_28",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Saadati v. Moorhead",
    shortTitle: "Saadati",
    citation: "Saadati v. Moorhead, 2017 SCC 28",
    neutralCitation: "2017 SCC 28",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 2017,
    bindingWeight: "binding",
    importanceScore: 90,
    confidence: "high",
    courtPaths: ["civil", "small-claims"],
    legalDomains: ["negligence", "personal-injury"],
    proceduralStages: ["pre-litigation", "starting-case", "trial"],
    topicTags: ["mental injury", "negligence damages", "proof of harm"],
    doctrineTags: ["mental-injury", "damages"],
    ruleReferences: [],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Mental injury can be compensable in negligence without requiring proof of a recognized psychiatric illness, but serious and prolonged disturbance must still be proven.",
    plainLanguageSummary:
      "This case matters when someone claims mental injury or psychological harm from negligence.",
    legalTestSummary:
      "The user still needs evidence showing a real, serious, and prolonged mental injury connected to the defendant’s conduct.",
    howCourtsUseIt: [
      "To assess mental injury damages.",
      "To avoid requiring a specific psychiatric diagnosis as a strict legal threshold.",
    ],
    practicalUse: [
      "Collect records and witness evidence showing actual impact over time.",
    ],
    commonMistakes: [
      "Assuming stress alone proves legal damages.",
      "Failing to connect the harm to the defendant’s conduct.",
    ],
    limitsAndWarnings: [
      "Proof of seriousness, duration, and causation is still required.",
    ],
    legalTestElements: [
      {
        id: "saadati_serious_prolonged",
        label: "Serious and prolonged mental injury",
        explanation: "The harm must be more than ordinary upset or frustration.",
        proofNeeded: ["Medical records if available", "witness evidence", "daily-life impact"],
        commonWeaknesses: ["Vague emotional harm with no examples"],
        evidenceExamples: ["Doctor notes", "therapy records", "family/witness statements"],
        burdenRelevance: "Plaintiff/user must prove harm and causation.",
      },
    ],
    evidenceImplications: [
      {
        id: "saadati_impact_evidence",
        label: "Impact evidence",
        explanation: "Evidence should show actual functional impact.",
        evidenceUsuallyNeeded: ["Records", "witnesses", "timeline of symptoms"],
        weakEvidenceWarnings: ["Only saying 'I was stressed'"],
        strongEvidenceExamples: ["Consistent treatment records and witness observations"],
      },
    ],
    workflowLinks: [
      { route: "/evidence", reason: "Collect harm and causation proof." },
      { route: "/litigation-strategy", reason: "Assess damages strength." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: [],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not say mental injury is proven without evidence of seriousness and causation."],
    },
    suggestedAiQuestions: [
      "What harm did you experience and how long did it last?",
      "Do you have records or witnesses showing the impact?",
    ],
    suggestedEvidenceQuestions: [
      "Do you have medical notes, therapy records, or people who observed the change?",
    ],
    suggestedWorkflowActions: ["Build damages evidence.", "Map causation."],
    sourceReferences: [
      {
        id: "src_saadati_canlii",
        sourceType: "canlii",
        title: "Saadati v. Moorhead",
        citationOrUrlLabel: "2017 SCC 28",
        notes: ["Verified SCC/CanLII authority."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_family_gordon_v_goertz_1996_scc",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Gordon v. Goertz",
    shortTitle: "Gordon",
    citation: "Gordon v. Goertz, [1996] 2 S.C.R. 27",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 1996,
    bindingWeight: "binding",
    importanceScore: 90,
    confidence: "high",
    courtPaths: ["family"],
    legalDomains: ["family-parenting"],
    proceduralStages: ["motion", "trial"],
    topicTags: ["best interests", "mobility", "parenting"],
    doctrineTags: ["best-interests-child"],
    ruleReferences: [],
    statuteReferences: ["Divorce Act"],
    formReferences: [],
    corePrinciple:
      "Parenting decisions must be child-centred and based on the best interests of the child.",
    plainLanguageSummary:
      "This case matters when a parenting issue asks what arrangement best serves the child, especially mobility or changes to parenting arrangements.",
    legalTestSummary:
      "The focus is the child’s best interests, not either parent’s preferences alone.",
    howCourtsUseIt: [
      "To assess child-centred parenting disputes.",
      "To examine changes in circumstances and the child’s needs.",
    ],
    practicalUse: [
      "Organize facts around the child’s stability, care, school, relationships, and safety.",
    ],
    commonMistakes: [
      "Making the case mostly about adult conflict instead of the child.",
    ],
    limitsAndWarnings: [
      "Family law is fact-specific and current statutory language must also be checked.",
    ],
    legalTestElements: [
      {
        id: "gordon_best_interests",
        label: "Best interests",
        explanation: "The court focuses on the child’s welfare and circumstances.",
        proofNeeded: ["Child’s schedule", "care history", "school", "health", "family supports"],
        commonWeaknesses: ["Parent-focused allegations without child impact"],
        evidenceExamples: ["Parenting schedule", "school records", "messages about care"],
        burdenRelevance: "Party seeking change must support why it benefits the child.",
      },
    ],
    evidenceImplications: [
      {
        id: "gordon_child_focused_evidence",
        label: "Child-focused evidence",
        explanation: "Evidence should show how the requested order affects the child.",
        evidenceUsuallyNeeded: ["Current schedule", "status quo", "care records"],
        weakEvidenceWarnings: ["General conflict without child-specific facts"],
        strongEvidenceExamples: ["Consistent caregiving history and child needs evidence"],
      },
    ],
    workflowLinks: [
      { route: "/builder", reason: "Clarify child-focused facts." },
      { route: "/evidence", reason: "Collect parenting evidence." },
      { route: "/court-package", reason: "Prepare materials after best-interests facts are organized." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: [],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not frame parenting strategy as punishment of the other parent."],
    },
    suggestedAiQuestions: [
      "What parenting arrangement is currently happening?",
      "What order are you asking for and why is it better for the child?",
    ],
    suggestedEvidenceQuestions: [
      "What records show the child’s routine, care, school, or safety needs?",
    ],
    suggestedWorkflowActions: ["Build child-focused facts.", "Prepare parenting evidence."],
    sourceReferences: [
      {
        id: "src_gordon_canlii",
        sourceType: "canlii",
        title: "Gordon v. Goertz",
        citationOrUrlLabel: "1996 CanLII 191 (SCC)",
        notes: ["Verified SCC/CanLII authority."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_admin_vavilov_2019_scc_65",
    version: "1.0.0",
    kind: "case-law",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "lawyer-review-recommended",
    title: "Canada (Minister of Citizenship and Immigration) v. Vavilov",
    shortTitle: "Vavilov",
    citation: "Canada (Minister of Citizenship and Immigration) v. Vavilov, 2019 SCC 65",
    neutralCitation: "2019 SCC 65",
    courtLevel: "supreme-court-of-canada",
    jurisdiction: "Canada",
    year: 2019,
    bindingWeight: "binding",
    importanceScore: 95,
    confidence: "high",
    courtPaths: ["civil", "tribunal", "immigration"],
    legalDomains: ["procedural", "immigration", "civil-institutional-liability"],
    proceduralStages: ["appeal", "motion", "trial"],
    topicTags: ["judicial review", "administrative law", "reasonableness"],
    doctrineTags: ["standard-of-review", "reasonableness-review"],
    ruleReferences: [],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Sets the modern framework for judicial review and reasonableness review of administrative decisions.",
    plainLanguageSummary:
      "This case matters when someone challenges a government or tribunal decision.",
    legalTestSummary:
      "The focus is usually whether the decision is reasonable and justified in light of the law and record.",
    howCourtsUseIt: [
      "To assess administrative decision-making.",
      "To review reasons and legal constraints.",
    ],
    practicalUse: [
      "Collect the full decision, record, reasons, correspondence, and governing statute.",
    ],
    commonMistakes: [
      "Arguing judicial review like a fresh trial.",
      "Not getting the decision record.",
    ],
    limitsAndWarnings: [
      "Judicial review is technical and deadline-sensitive.",
    ],
    legalTestElements: [
      {
        id: "vavilov_record_reasons",
        label: "Record and reasons",
        explanation: "The court reviews the decision in light of the record and legal constraints.",
        proofNeeded: ["Decision", "reasons", "record before decision-maker", "governing statute"],
        commonWeaknesses: ["Missing record"],
        evidenceExamples: ["Decision letter", "tribunal record", "submissions"],
        burdenRelevance: "Applicant must show reviewable error.",
      },
    ],
    evidenceImplications: [
      {
        id: "vavilov_decision_record",
        label: "Administrative record",
        explanation: "The record is central to judicial review.",
        evidenceUsuallyNeeded: ["Decision", "reasons", "record", "submissions"],
        weakEvidenceWarnings: ["Only describing unfairness without the decision record"],
        strongEvidenceExamples: ["Complete tribunal/government record"],
      },
    ],
    workflowLinks: [
      { route: "/builder", reason: "Identify decision and decision-maker." },
      { route: "/evidence", reason: "Collect record." },
      { route: "/litigation-strategy", reason: "Assess judicial review path." },
    ],
    relatedAuthorities: {
      follows: [],
      followedBy: [],
      distinguishes: [],
      distinguishedBy: [],
      limits: [],
      limitedBy: [],
      overrules: [],
      overruledBy: [],
      related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: true,
      mustVerifyBeforeCitation: false,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: ["Do not treat judicial review as a full rehearing."],
    },
    suggestedAiQuestions: [
      "What decision are you challenging?",
      "Who made the decision?",
      "When did you receive it?",
    ],
    suggestedEvidenceQuestions: [
      "Do you have the decision, reasons, and record?",
    ],
    suggestedWorkflowActions: ["Check deadline.", "Collect record.", "Review judicial review path."],
    sourceReferences: [
      {
        id: "src_vavilov_canlii",
        sourceType: "canlii",
        title: "Vavilov",
        citationOrUrlLabel: "2019 SCC 65",
        notes: ["Verified CanLII/SCC authority."],
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
    lastVerifiedAt: NOW,
  },

  {
    id: "authority_ontario_small_claims_jurisdiction_oreg_626_00_s1",
    version: "1.0.0",
    kind: "regulation",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "O. Reg. 626/00, Small Claims Court Jurisdiction and Appeal Limit, s. 1",
    shortTitle: "O. Reg. 626/00, s. 1",
    citation: "O. Reg. 626/00, Small Claims Court Jurisdiction and Appeal Limit, s. 1",
    courtLevel: "other",
    jurisdiction: "Ontario",
    bindingWeight: "binding",
    importanceScore: 90,
    confidence: "high",
    courtPaths: ["small-claims"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["pre-litigation", "starting-case"],
    topicTags: ["small claims", "monetary jurisdiction", "jurisdiction"],
    doctrineTags: ["small-claims-jurisdiction"],
    ruleReferences: [],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Confirm monetary jurisdiction before treating Ontario Small Claims as the correct path.",
    plainLanguageSummary:
      "This regulation is a prompt to verify the monetary jurisdiction before relying on the Ontario Small Claims path.",
    legalTestSummary:
      "This record does not decide whether a particular claim qualifies; the applicable amount and surrounding facts must be verified.",
    howCourtsUseIt: [
      "As the binding regulation governing the Small Claims Court jurisdiction and appeal limit.",
    ],
    practicalUse: [
      "Confirm the current monetary jurisdiction before selecting or continuing on the Ontario Small Claims path.",
    ],
    commonMistakes: [
      "Treating this record as a conclusion that a user is eligible for Small Claims Court.",
    ],
    limitsAndWarnings: [
      "Verify the applicable amount, remedy, parties, timing, interest, costs, and facts.",
      "Do not decide eligibility, damages, waiver, remedy, or forum from this record alone.",
      "Source currentness is limited to the source-check date recorded below.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Confirm monetary jurisdiction before treating Ontario Small Claims as the correct path.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not state that a user is eligible for Ontario Small Claims Court.",
        "Do not decide damages, waiver, remedy, or forum from this record.",
      ],
    },
    suggestedAiQuestions: [
      "What monetary amount is being claimed?",
      "What remedy and parties are involved?",
    ],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Verify monetary jurisdiction before choosing the Small Claims path."],
    sourceReferences: [
      {
        id: "src_ontario_oreg_626_00",
        sourceType: "ontario-elaws",
        title: "O. Reg. 626/00, Small Claims Court Jurisdiction and Appeal Limit",
        citationOrUrlLabel: "Ontario e-Laws",
        sourceUrl: "https://www.ontario.ca/laws/regulation/000626",
        pinpoint: "s. 1",
        verifiedAt: "2026-08-06",
        notes: ["Official Ontario source checked on 2026-08-06."],
      },
      {
        id: "src_ontario_oreg_626_00_amendment_2025",
        sourceType: "ontario-elaws",
        title: "O. Reg. 42/25",
        citationOrUrlLabel: "Ontario e-Laws current amendment",
        sourceUrl: "https://www.ontario.ca/laws/regulation/r25042",
        pinpoint: "s. 1; commencement s. 3",
        verifiedAt: "2026-08-06",
        notes: ["Current amendment source checked on 2026-08-06."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },

  {
    id: "authority_ontario_small_claims_procedure_guide",
    version: "1.0.0",
    kind: "official-guide",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Guide to procedures in Small Claims Court",
    shortTitle: "Small Claims procedure guide",
    citation: "Guide to procedures in Small Claims Court",
    courtLevel: "small-claims-court",
    jurisdiction: "Ontario",
    bindingWeight: "procedural-guidance",
    importanceScore: 75,
    confidence: "high",
    courtPaths: ["small-claims"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["pre-litigation", "starting-case", "responding", "already-started"],
    topicTags: ["small claims", "procedure", "official guidance"],
    doctrineTags: ["small-claims-procedure-guidance"],
    ruleReferences: [],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "The guide helps identify procedural information and official forms, but does not replace the Rules of the Small Claims Court or legal advice.",
    plainLanguageSummary:
      "Use this official guide to locate procedural information and official forms, while verifying the governing Rules and obtaining legal advice when needed.",
    legalTestSummary:
      "This non-binding guide does not determine legal rights, obligations, eligibility, or outcomes.",
    howCourtsUseIt: [],
    practicalUse: [
      "Use the guide to identify procedural information and official forms for an Ontario Small Claims matter.",
    ],
    commonMistakes: [
      "Treating the guide as a statute, court rule, precedent, or legal advice.",
    ],
    limitsAndWarnings: [
      "This guide is non-binding official guidance, not a statute, court rule, or precedent.",
      "It does not replace the Rules of the Small Claims Court or legal advice.",
      "Source currentness is limited to the source-check date recorded below.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Identify relevant procedure and official forms through the guide without treating it as legal advice.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not treat this guidance as a statute, court rule, or precedent.",
        "Do not present this guidance as legal advice or a legal eligibility conclusion.",
      ],
    },
    suggestedAiQuestions: ["What procedural information or official form are you looking for?"],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Consult the official guide, then verify the applicable Rules of the Small Claims Court."],
    sourceReferences: [
      {
        id: "src_ontario_small_claims_procedure_guide",
        sourceType: "official-court",
        title: "Guide to procedures in Small Claims Court",
        citationOrUrlLabel: "Ontario official guidance",
        sourceUrl: "https://www.ontario.ca/document/guide-procedures-small-claims-court",
        pinpoint: "overview / forms-and-procedure guidance section",
        verifiedAt: "2026-08-06",
        notes: ["Official Ontario guidance source checked on 2026-08-06."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },

  {
    id: "authority_ontario_family_law_rules_oreg_114_99",
    version: "1.0.0",
    kind: "rule",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "O. Reg. 114/99, Family Law Rules",
    shortTitle: "Family Law Rules",
    citation: "O. Reg. 114/99, Family Law Rules",
    courtLevel: "other",
    jurisdiction: "Ontario",
    bindingWeight: "binding",
    importanceScore: 90,
    confidence: "high",
    courtPaths: ["family"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["pre-litigation", "starting-case", "responding", "already-started", "conference", "motion", "trial", "enforcement", "appeal", "urgent", "settlement", "not-sure"],
    topicTags: ["family", "procedure", "family law rules"],
    doctrineTags: ["family-procedure"],
    ruleReferences: ["O. Reg. 114/99, Family Law Rules"],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Applicable Ontario Family Court procedure must be determined by the Family Law Rules and the case's current stage.",
    plainLanguageSummary:
      "Use the Family Law Rules to identify the procedure that may apply at the case's current stage, without treating this record as a conclusion about a particular step or outcome.",
    legalTestSummary:
      "This record does not determine a particular form, deadline, remedy, parenting arrangement, support amount, or outcome.",
    howCourtsUseIt: [
      "As the binding procedural rules for Ontario Family Court matters within their applicable scope.",
    ],
    practicalUse: [
      "Confirm the Ontario Family court path and current stage, then verify the applicable Family Law Rules before taking a procedural step.",
    ],
    commonMistakes: [
      "Treating this record as proof that a particular form, deadline, remedy, parenting arrangement, support amount, or outcome applies.",
    ],
    limitsAndWarnings: [
      "Confirm the Ontario Family court path and current stage before relying on this record.",
      "Verify the applicable rule, form, deadline, remedy, facts, and procedural requirements for the specific matter.",
      "Do not decide a parenting arrangement, support amount, property result, remedy, or outcome from this record alone.",
      "Source currentness is limited to the source-check date recorded below; this registry does not perform live verification or legal-merits review.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Confirm the Ontario Family court path and current stage, then verify the applicable Family Law Rules.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not state that a particular form, deadline, remedy, parenting arrangement, support amount, or outcome applies.",
        "Do not bypass court-path, stage, source, permission, or currentness checks.",
      ],
    },
    suggestedAiQuestions: [
      "What is the Ontario Family Court stage of the case?",
      "What procedural step are you considering?",
    ],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Verify the applicable Family Law Rules for the confirmed Ontario Family court path and current stage."],
    sourceReferences: [
      {
        id: "src_ontario_family_law_rules_oreg_114_99",
        sourceType: "ontario-elaws",
        title: "O. Reg. 114/99, Family Law Rules",
        citationOrUrlLabel: "Ontario e-Laws",
        sourceUrl: "https://www.ontario.ca/laws/regulation/990114",
        pinpoint: "Family Law Rules; applicable procedure depends on the current stage",
        verifiedAt: "2026-08-06",
        notes: ["Source-check date recorded as 2026-08-06; no live verification or legal-merits review is performed by this registry."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },

  {
    id: "authority_ontario_family_procedure_guide",
    version: "1.0.0",
    kind: "official-guide",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Guide to procedures in family court",
    shortTitle: "Family court procedure guide",
    citation: "Guide to procedures in family court",
    courtLevel: "other",
    jurisdiction: "Ontario",
    bindingWeight: "procedural-guidance",
    importanceScore: 75,
    confidence: "high",
    courtPaths: ["family"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["pre-litigation", "starting-case", "responding", "already-started", "conference", "motion", "trial", "enforcement", "appeal", "urgent", "settlement", "not-sure"],
    topicTags: ["family", "procedure", "official guidance"],
    doctrineTags: ["family-procedure-guidance"],
    ruleReferences: ["O. Reg. 114/99, Family Law Rules"],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "The official guide can help a user understand procedural steps and locate court resources, but does not replace the Family Law Rules or legal advice.",
    plainLanguageSummary:
      "Use this official guide to understand procedural steps and locate court resources, while verifying the Family Law Rules and obtaining legal advice when needed.",
    legalTestSummary:
      "This non-binding guide does not determine legal rights, obligations, forms, deadlines, remedies, parenting arrangements, support amounts, or outcomes.",
    howCourtsUseIt: [],
    practicalUse: [
      "Use the guide to understand procedural steps and locate court resources for an Ontario Family matter.",
    ],
    commonMistakes: [
      "Treating the guide as a court rule, legal advice, or a conclusion that a particular form, deadline, remedy, or outcome applies.",
    ],
    limitsAndWarnings: [
      "This guide is non-binding official guidance, not a court rule, statute, or precedent.",
      "It does not replace the Family Law Rules or legal advice.",
      "Confirm the Ontario Family court path and current stage before relying on this guide.",
      "Source currentness is limited to the source-check date recorded below; this registry does not perform live verification or legal-merits review.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Use the official guide to understand procedural steps and locate court resources after confirming the Ontario Family court path and current stage.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not treat this guidance as a statute, court rule, or precedent.",
        "Do not present this guidance as legal advice or a conclusion that a particular form, deadline, remedy, parenting arrangement, support amount, or outcome applies.",
        "Do not bypass court-path, stage, source, permission, or currentness checks.",
      ],
    },
    suggestedAiQuestions: ["What procedural step or court resource are you looking for?", "What is the Ontario Family Court stage of the case?"],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Consult the official guide, then verify the applicable Family Law Rules for the confirmed stage."],
    sourceReferences: [
      {
        id: "src_ontario_family_procedure_guide",
        sourceType: "official-court",
        title: "Guide to procedures in family court",
        citationOrUrlLabel: "Ontario official guidance",
        sourceUrl: "https://www.ontario.ca/document/guide-procedures-family-court",
        pinpoint: "guide overview / starting-family-case procedure guidance",
        verifiedAt: "2026-08-06",
        notes: ["Source-check date recorded as 2026-08-06; no live verification or legal-merits review is performed by this registry."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },

  {
    id: "authority_ontario_rules_civil_procedure_rro_1990_reg_194_r_1_02",
    version: "1.0.0",
    kind: "rule",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "R.R.O. 1990, Reg. 194, Rules of Civil Procedure, r. 1.02",
    shortTitle: "Rules of Civil Procedure, r. 1.02",
    citation: "R.R.O. 1990, Reg. 194, Rules of Civil Procedure, r. 1.02",
    courtLevel: "other",
    jurisdiction: "Ontario",
    bindingWeight: "binding",
    importanceScore: 90,
    confidence: "high",
    courtPaths: ["civil"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["pre-litigation", "starting-case", "responding", "already-started", "conference", "motion", "trial", "enforcement", "appeal", "urgent", "settlement", "not-sure"],
    topicTags: ["civil", "procedure", "rules of civil procedure"],
    doctrineTags: ["civil-procedure"],
    ruleReferences: ["R.R.O. 1990, Reg. 194, Rules of Civil Procedure, r. 1.02"],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "The Rules govern applicable civil proceedings in the Superior Court of Justice, subject to their stated exceptions.",
    plainLanguageSummary:
      "Use the Rules of Civil Procedure to identify procedure that may apply in an Ontario Civil Superior Court matter, while preserving their stated distinction for Small Claims Court and Family Law Rules proceedings.",
    legalTestSummary:
      "This record does not determine a particular procedure, form, deadline, remedy, merits issue, or case-specific outcome.",
    howCourtsUseIt: [
      "As the binding procedural rules for applicable civil proceedings in the Superior Court of Justice, subject to the Rules' stated exceptions.",
    ],
    practicalUse: [
      "Confirm the Ontario Civil court path and current stage, then verify the applicable Rule before taking a procedural step.",
    ],
    commonMistakes: [
      "Treating this record as proof that the Rules govern a Small Claims Court or Family Law Rules proceeding, or that a particular procedure, form, deadline, remedy, or outcome applies.",
    ],
    limitsAndWarnings: [
      "Rule 1.02 states that the Rules do not govern proceedings in the Small Claims Court or proceedings to which the Family Law Rules apply, except as the Rules provide.",
      "Confirm the Ontario Civil court path and current stage before relying on this record.",
      "Verify the applicable rule, form, deadline, remedy, facts, and procedural requirements for the specific matter.",
      "Do not decide merits, liability, damages, remedy, or outcome from this record alone.",
      "Source currentness is limited to the source-check date recorded below; this registry does not perform live verification or legal-merits review.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Confirm the Ontario Civil court path and current stage, then verify the applicable Rules of Civil Procedure.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not state that a particular procedure, form, deadline, remedy, or outcome applies.",
        "Do not treat this record as governing Small Claims Court or Family Law Rules proceedings except as the Rules provide.",
        "Do not bypass court-path, stage, source, permission, or currentness checks.",
      ],
    },
    suggestedAiQuestions: [
      "What is the Ontario Civil stage of the case?",
      "What procedural step are you considering?",
    ],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Verify the applicable Rules of Civil Procedure for the confirmed Ontario Civil court path and current stage."],
    sourceReferences: [
      {
        id: "src_ontario_rules_civil_procedure_rro_1990_reg_194_r_1_02",
        sourceType: "ontario-elaws",
        title: "R.R.O. 1990, Reg. 194, Rules of Civil Procedure",
        citationOrUrlLabel: "Ontario e-Laws",
        sourceUrl: "https://www.ontario.ca/laws/regulation/900194",
        pinpoint: "r. 1.02",
        verifiedAt: "2026-08-06",
        notes: ["Source-check date recorded as 2026-08-06; no live verification or legal-merits review is performed by this registry."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },

  {
    id: "authority_ontario_civil_claims_suing_and_being_sued_guide",
    version: "1.0.0",
    kind: "official-guide",
    displayMode: "collapsed",
    verificationStatus: "verified",
    userRiskLevel: "needs-context",
    title: "Civil claims: suing and being sued",
    shortTitle: "Civil claims guide",
    citation: "Civil claims: suing and being sued",
    courtLevel: "other",
    jurisdiction: "Ontario",
    bindingWeight: "procedural-guidance",
    importanceScore: 75,
    confidence: "high",
    courtPaths: ["civil"],
    legalDomains: ["procedural"],
    appliesAcrossIssueDomains: true,
    proceduralStages: ["starting-case"],
    topicTags: ["civil", "procedure", "official guidance"],
    doctrineTags: ["civil-procedure-guidance"],
    ruleReferences: ["R.R.O. 1990, Reg. 194, Rules of Civil Procedure"],
    statuteReferences: [],
    formReferences: [],
    corePrinciple:
      "Official Ontario guidance can help identify general civil-procedure information, but does not replace the Rules of Civil Procedure or legal advice.",
    plainLanguageSummary:
      "Use this official guidance to identify general steps for a civil case started by statement of claim, while verifying the Rules of Civil Procedure and obtaining legal advice when needed.",
    legalTestSummary:
      "This non-binding guide does not determine legal rights, obligations, procedure, forms, deadlines, remedies, merits, or outcomes.",
    howCourtsUseIt: [],
    practicalUse: [
      "Use the guidance to identify general civil-procedure information for a case started by statement of claim.",
    ],
    commonMistakes: [
      "Treating the guide as a court rule, legal advice, or a conclusion that a particular procedure, form, deadline, remedy, or outcome applies.",
    ],
    limitsAndWarnings: [
      "This guide is non-binding official guidance, not a court rule, statute, or precedent.",
      "It does not replace the Rules of Civil Procedure or legal advice.",
      "Confirm the Ontario Civil court path and current stage before relying on this guide.",
      "Source currentness is limited to the source-check date recorded below; this registry does not perform live verification or legal-merits review.",
    ],
    legalTestElements: [],
    evidenceImplications: [],
    workflowLinks: [
      { route: "/builder", reason: "Use the official guidance to identify general civil-procedure information after confirming the Ontario Civil court path and starting-case stage.", stage: "starting-case" },
    ],
    relatedAuthorities: {
      follows: [], followedBy: [], distinguishes: [], distinguishedBy: [], limits: [],
      limitedBy: [], overrules: [], overruledBy: [], related: [],
    },
    annualPracticeLinks: [],
    aiUseRules: {
      canShowToUser: true,
      canUseForReasoning: true,
      canUseForDrafting: false,
      mustVerifyBeforeCitation: true,
      mustExplainLimits: true,
      mustAskContextQuestions: true,
      prohibitedUses: [
        "Do not treat this guidance as a statute, court rule, or precedent.",
        "Do not present this guidance as legal advice or a conclusion that a particular procedure, form, deadline, remedy, or outcome applies.",
        "Do not bypass court-path, stage, source, permission, or currentness checks.",
      ],
    },
    suggestedAiQuestions: ["What general civil-procedure information are you looking for?", "Is the Ontario Civil case being started by statement of claim?"],
    suggestedEvidenceQuestions: [],
    suggestedWorkflowActions: ["Consult the official guidance, then verify the applicable Rules of Civil Procedure for the confirmed stage."],
    sourceReferences: [
      {
        id: "src_ontario_civil_claims_suing_and_being_sued_guide",
        sourceType: "official-court",
        title: "Civil claims: suing and being sued",
        citationOrUrlLabel: "Ontario official guidance",
        sourceUrl: "https://www.ontario.ca/page/civil-claims-suing-and-being-sued",
        pinpoint: "general steps for civil cases started by statement of claim",
        verifiedAt: "2026-08-06",
        notes: ["Source-check date recorded as 2026-08-06; no live verification or legal-merits review is performed by this registry."],
      },
    ],
    createdAt: "2026-08-06T00:00:00.000Z",
    updatedAt: "2026-08-06T00:00:00.000Z",
    lastVerifiedAt: "2026-08-06T00:00:00.000Z",
  },
];

export const VERIFIED_AUTHORITY_TOPIC_GROUPS = [
  {
    id: "topic_defamation",
    label: "Defamation",
    description:
      "Authorities for reputation harm, publication, defences, responsible communication, fair comment, and anti-SLAPP context.",
    legalDomains: ["defamation"],
    courtPaths: ["civil", "small-claims"],
    authorityIds: [
      "authority_defamation_grant_v_torstar_2009_scc_61",
    ],
    defaultCollapsed: true,
  },
  {
    id: "topic_charter",
    label: "Charter",
    description:
      "Authorities for Charter limits, section 1 justification, arbitrariness, overbreadth, gross disproportionality, and state action.",
    legalDomains: ["civil-charter"],
    courtPaths: ["civil", "criminal-related"],
    authorityIds: ["authority_charter_oakes_1986_scc"],
    defaultCollapsed: true,
  },
  {
    id: "topic_civil_procedure",
    label: "Civil Procedure",
    description:
      "Authorities and procedural sources for summary judgment, proportionality, pleadings, service, motions, and court readiness.",
    legalDomains: ["procedural"],
    courtPaths: ["civil", "small-claims"],
    authorityIds: ["authority_civil_procedure_hryniak_2014_scc_7"],
    defaultCollapsed: true,
  },
  {
    id: "topic_negligence",
    label: "Negligence",
    description:
      "Authorities for duty, standard of care, causation, remoteness, damages, and proof of injury.",
    legalDomains: ["negligence", "personal-injury"],
    courtPaths: ["civil", "small-claims"],
    authorityIds: ["authority_negligence_saadati_2017_scc_28"],
    defaultCollapsed: true,
  },
  {
    id: "topic_family_parenting",
    label: "Family Parenting",
    description:
      "Authorities for parenting, best interests, mobility, status quo, safety, and child-focused evidence.",
    legalDomains: ["family-parenting"],
    courtPaths: ["family"],
    authorityIds: ["authority_family_gordon_v_goertz_1996_scc"],
    defaultCollapsed: true,
  },
  {
    id: "topic_administrative_public_authority",
    label: "Administrative / Public Authority",
    description:
      "Authorities for judicial review, administrative decisions, government actors, records, reasons, and review standards.",
    legalDomains: ["procedural", "immigration", "civil-institutional-liability"],
    courtPaths: ["civil", "tribunal", "immigration"],
    authorityIds: ["authority_admin_vavilov_2019_scc_65"],
    defaultCollapsed: true,
  },
] satisfies AuthorityRegistryModel["topicGroups"];

export const VERIFIED_AUTHORITY_SEED_REGISTRY: AuthorityRegistryModel = {
  version: "1.0.0",
  entries: VERIFIED_AUTHORITY_SEED_ENTRIES,
  topicGroups: VERIFIED_AUTHORITY_TOPIC_GROUPS,
  warnings: [
    "Starter registry only. Add Annual Practice authorities only after verified extraction.",
    "Do not display authorities marked internal-only or do-not-display.",
    "Do not cite authority text directly unless the source and pinpoint have been verified.",
  ],
};

export function getVerifiedAuthoritySeedRegistry(): AuthorityRegistryModel {
  return VERIFIED_AUTHORITY_SEED_REGISTRY;
}

export function getVerifiedAuthoritySeedEntries(): VerifiedAuthorityEntry[] {
  return VERIFIED_AUTHORITY_SEED_ENTRIES;
}
