/**
 * COURT OFFICE CLOSURES — "is the counter open?", which is not "does the clock move?".
 *
 * *** THE GAP THIS CLOSES ***
 *
 * `holidays.ts` models the holidays r. 1.02 names, and a deadline landing on one
 * moves. That is law, and it is right.
 *
 * On 2026-09-26 the ontario.ca filing page began stating that provincial court
 * offices are closed on Wednesday 30 September 2026, and that anything filed
 * online that day is marked filed on 1 October. **30 September is not an r. 1.02
 * holiday**, so the deadline does not move and the engine correctly says so — and
 * a user who files on their deadline that day holds a document stamped after it.
 *
 * Two different questions, two different provenances:
 *
 *   does the clock move?   -> r. 1.02, Legislation Act s. 88(2)   -> holidays.ts
 *   is the counter open?   -> ministry and court service notices  -> this file
 *
 * *** WHERE THE DATES COME FROM ***
 *
 * `courtServiceNotices.json`, generated by `scripts/rules/extractServiceNotices.ts`
 * from the vendored corpus, with the sentence each date was read from.
 * `test:service-notices` re-checks every quote against the corpus, so a date that
 * someone types in by hand fails a check instead of becoming true.
 *
 * *** WHY A STALE NOTICE IS THE LIKELY FAILURE, NOT A MISSING ONE ***
 *
 * The filing page still carries its 2025 closure alongside the 2026 one. Closures
 * are announced per occasion and never removed, so the file will accumulate past
 * dates forever. Everything here therefore filters by date rather than by
 * position or recency, and a notice in the past is simply not a warning.
 */

import noticesFile from "./courtServiceNotices.json";
import { fillTemplate, type DeadlineTemplateId } from "./deadlineTemplates";
/*
 * From holidays.ts, which is where both of these are actually declared.
 * deadlineEngine re-exports them and importing them THROUGH it typechecked
 * cleanly while `formatLongDate` arrived as undefined at runtime — a circular
 * import resolved in tsc's favour and not in Node's. Importing from the
 * declaring module costs nothing and cannot do that.
 */
import { formatLongDate, type IsoDate } from "./holidays";

export type CourtServiceNotice = {
  closedOn: string;
  occasion: string;
  stampedAs: string | null;
  portalAvailable: boolean | null;
  sourceId: string;
  sourceUrl: string;
  quote: string;
  weekdayStated: string;
  corroboratedBy?: string[];
};

export const COURT_SERVICE_NOTICES: readonly CourtServiceNotice[] = (
  noticesFile as { notices: CourtServiceNotice[] }
).notices;

/**
 * How far before a closure a deadline still earns a warning.
 *
 * Three BUSINESS days, per the decision recorded in the report. The point is not
 * the arithmetic: it is that somebody who plans to file "around" their deadline
 * needs to know a shut day is coming, because the shut day will not count as the
 * day they filed.
 */
export const WARN_WITHIN_BUSINESS_DAYS = 3;

/**
 * Business days between two dates, counting Monday to Friday only.
 *
 * *** THIS DELIBERATELY IGNORES HOLIDAYS, AND THAT IS NOT A SHORTCUT ***
 *
 * It would be easy to reuse the r. 1.02 holiday list here and feel more precise.
 * It would also be wrong in kind: this number decides whether to SHOW A WARNING,
 * not what any deadline is. Using the legal holiday calendar to size a warning
 * window would tangle the two calendars this file exists to keep apart, and the
 * only effect would be to make the window occasionally a day wider or narrower.
 * Nothing legal turns on it, so it stays a plain weekday count that anyone can
 * check by eye.
 */
export function businessDaysBetween(from: string, to: string): number {
  if (to <= from) return 0;
  let count = 0;
  const cursor = new Date(`${from}T00:00:00Z`);
  const end = new Date(`${to}T00:00:00Z`);
  while (cursor < end) {
    cursor.setUTCDate(cursor.getUTCDate() + 1);
    const day = cursor.getUTCDay();
    if (day !== 0 && day !== 6) count += 1;
  }
  return count;
}

export type ClosureWarning = {
  templateId: DeadlineTemplateId;
  values: Record<string, string>;
  notice: CourtServiceNotice;
  /** True when the deadline IS the closure day, rather than shortly before it. */
  onTheDay: boolean;
};

/**
 * The closure warning for a rendered deadline, or null when there is none.
 *
 * Returns the template and its values rather than a string, so the sentence is
 * still one of the fixed reviewed templates and still passes through the output
 * guard the same way every other deadline sentence does.
 */
export function closureWarningFor(
  deadline: IsoDate | string,
  notices: readonly CourtServiceNotice[] = COURT_SERVICE_NOTICES,
): ClosureWarning | null {
  const candidates = notices
    .filter((notice) => {
      // A closure the deadline has already passed is not a warning.
      if (notice.closedOn < deadline) return false;
      if (notice.closedOn === deadline) return true;
      return businessDaysBetween(deadline, notice.closedOn) <= WARN_WITHIN_BUSINESS_DAYS;
    })
    // The nearest closure is the one that matters.
    .sort((a, b) => a.closedOn.localeCompare(b.closedOn));

  const notice = candidates[0];
  if (!notice) return null;

  /*
   * A notice with no stamping date cannot carry either sentence: both of them
   * tell the reader WHICH day the filing would be recorded on, and that is the
   * whole point. Saying "it will be stamped later" without saying when would be
   * an alarm with no information in it.
   */
  if (!notice.stampedAs) return null;

  const onTheDay = notice.closedOn === deadline;
  const templateId: DeadlineTemplateId = onTheDay
    ? "court-office-closed-on-this-date"
    : "court-office-closes-soon-after-this-date";

  return {
    templateId,
    onTheDay,
    notice,
    values: {
      closedOn: formatLongDate(notice.closedOn as IsoDate),
      stampedAs: formatLongDate(notice.stampedAs as IsoDate),
      occasion: notice.occasion,
      source: notice.sourceUrl,
    },
  };
}

/** The rendered warning sentence, or null. */
export function closureWarningProse(
  deadline: IsoDate | string,
  notices: readonly CourtServiceNotice[] = COURT_SERVICE_NOTICES,
): string | null {
  const warning = closureWarningFor(deadline, notices);
  if (!warning) return null;
  return fillTemplate(warning.templateId, warning.values);
}
