-- case_event_candidate_dismissals — the rejection ledger for event candidates.
--
-- WHY THIS EXISTS. A narrative-parsed event is a CANDIDATE, not an event: the
-- case_events source CHECK has no 'system-inference' value, so a parse cannot
-- become a row until a user confirms it. That leaves three states a candidate
-- can be in, and two of them were previously indistinguishable:
--
--   confirmed  -> a case_events row exists
--   dismissed  -> the user said no
--   unanswered -> the user has not said anything
--
-- Without a record of dismissal, a rejected candidate looks exactly like an
-- unanswered one and gets re-offered forever.
--
-- WHY ONLY DISMISSALS ARE STORED. Confirmed candidates are already recorded, as
-- case_events rows. Unanswered candidates need no storage — they are cheap to
-- recompute from the narrative, and storing them would create somewhere for
-- silence to be written down. Silence is not "no". A candidate the user never
-- answered must stay answerable indefinitely, and the surest way to guarantee
-- that is to have nowhere to record that they didn't.
--
-- WHY A FINGERPRINT AND NOT A CANDIDATE ID. Candidate ids are generated by
-- nowId() in aiIntakeNormalizer.ts as `timeline_<Date.now()>_<random>` — a
-- fresh id on every parse for the same sentence. A dismissal keyed on id would
-- match nothing after a re-parse and the candidate would return. The
-- fingerprint is over the SENTENCE, which is what the user actually rejected:
-- re-parsing the same narrative reproduces it, and editing the narrative
-- changes it, which correctly re-offers a candidate that is now different.
--
-- The failure mode is deliberate. A near-miss (whitespace, a reworded sentence)
-- re-offers a dismissed candidate, which is mildly annoying. The opposite
-- failure — silently suppressing a real event the user wanted — is worse.
--
-- ENVIRONMENT: dev (courtsimplified-dev, fddlpnibovkkkgboabqb, ca-central-1).
-- Production (ffymjxjcnwakgdmldpne) is a separate decision under CLAUDE.md
-- section 6 and is NOT covered by this migration.

CREATE TABLE IF NOT EXISTS "public"."case_event_candidate_dismissals" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "case_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,

    -- sha256 over the normalized narrative SENTENCE alone — not the candidate
    -- id (regenerated on every parse) and not the event type (candidates carry
    -- none, because the parser does not classify; hashing a type in would let
    -- the same rejected sentence reappear under a different suggested type).
    -- Computed in candidateFingerprint(); see that function for what is
    -- normalized and why the normalization is deliberately conservative.
    "candidate_fingerprint" "text" NOT NULL,

    -- Kept readable alongside the hash so a dismissal can be shown back to the
    -- user, and so a maintainer can see what was rejected without recomputing.
    "narrative_basis" "text" NOT NULL,
    -- Nullable: candidates carry no type, so a dismissal usually has none.
    -- Present only where a future source supplies one honestly.
    "suggested_event_type" "text",

    "dismissed_at" timestamp with time zone DEFAULT "now"() NOT NULL,

    -- Reversible by design. A user who dismisses something and later realises
    -- it did happen gets it back. Append-style rather than a delete, matching
    -- case_events: the record shows both the dismissal and the restoration.
    "restored_at" timestamp with time zone,

    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,

    CONSTRAINT "case_event_candidate_dismissals_fingerprint_present"
        CHECK (("length"("candidate_fingerprint") = 64)),

    CONSTRAINT "case_event_candidate_dismissals_basis_present"
        CHECK (("length"("btrim"("narrative_basis")) > 0)),

    -- A restoration cannot precede the dismissal it reverses.
    CONSTRAINT "case_event_candidate_dismissals_restore_after_dismiss"
        CHECK (("restored_at" IS NULL) OR ("restored_at" >= "dismissed_at"))
);


ALTER TABLE "public"."case_event_candidate_dismissals" OWNER TO "postgres";


COMMENT ON TABLE "public"."case_event_candidate_dismissals" IS
    'Records event candidates a user has explicitly rejected. Dismissals ONLY — confirmed candidates become case_events rows, and unanswered candidates are stored nowhere, so that silence can never be written down as an answer.';

COMMENT ON COLUMN "public"."case_event_candidate_dismissals"."candidate_fingerprint" IS
    'sha256 of the normalized narrative sentence alone. Keyed on content, not on candidate id: ids are regenerated on every parse, so an id-keyed dismissal would match nothing after a re-parse. The event type is deliberately excluded — candidates carry none, and including it would let the same rejected sentence reappear under a different suggested type.';

COMMENT ON COLUMN "public"."case_event_candidate_dismissals"."restored_at" IS
    'Non-null means the dismissal was reversed and the candidate is offered again. Recorded rather than deleted so the history stays auditable.';


ALTER TABLE ONLY "public"."case_event_candidate_dismissals"
    ADD CONSTRAINT "case_event_candidate_dismissals_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."case_event_candidate_dismissals"
    ADD CONSTRAINT "case_event_candidate_dismissals_case_id_fkey"
    FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."case_event_candidate_dismissals"
    ADD CONSTRAINT "case_event_candidate_dismissals_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- One live dismissal per fingerprint per case. A user dismissing the same
-- candidate twice is the same dismissal, not two.
CREATE UNIQUE INDEX "case_event_candidate_dismissals_live_idx"
    ON "public"."case_event_candidate_dismissals" ("case_id", "candidate_fingerprint")
    WHERE ("restored_at" IS NULL);

CREATE INDEX "case_event_candidate_dismissals_case_id_idx"
    ON "public"."case_event_candidate_dismissals" USING "btree" ("case_id");


ALTER TABLE "public"."case_event_candidate_dismissals" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own event candidate dismissals"
    ON "public"."case_event_candidate_dismissals"
    TO "authenticated"
    USING (("auth"."uid"() = "user_id"))
    WITH CHECK (("auth"."uid"() = "user_id"));


-- Matches the existing case_* grant convention. See OUTSTANDING_ISSUES.md
-- section 16: every case table grants ALL to anon and survives on RLS. Matched
-- here rather than diverging in one table.
GRANT ALL ON TABLE "public"."case_event_candidate_dismissals" TO "anon";
GRANT ALL ON TABLE "public"."case_event_candidate_dismissals" TO "authenticated";
GRANT ALL ON TABLE "public"."case_event_candidate_dismissals" TO "service_role";
