/**
 * Runs the 10 fabricated fixtures in fixtures/caseReviews/ through the
 * SAME real pipeline runFixtures.ts uses (pipelineRunner.ts -- no second,
 * independently-maintained copy of the turn loop), and writes one
 * full, human-readable "case review" markdown file per case, plus an
 * index that itemizes all 10 with a one-line description of what each is
 * built to test.
 *
 * This is deliberately NOT a pass/fail harness like runFixtures.ts or
 * runGeneratedFixtures.ts -- there are no .expected.md files here and
 * nothing is asserted automatically. The point is a full, itemized record
 * for manual review: the opening story, every fabricated document with
 * its description, the full question-and-answer transcript exactly as a
 * user would have seen it (question text shown, lead-in shown, answer
 * given), the claim type and evidence guidance at each turn, and the
 * complete final AnalysisResult -- so a person can read what the system
 * was asked, what it said back, and how it organized the evidence, for
 * 10 different case shapes at once.
 *
 * Real, billed OpenAI calls throughout, same as runFixtures.ts -- this is
 * the real pipeline, not a stub of it. 10 full guided-intake conversations
 * (9-14 turns each) plus 10 final brain analyses is a meaningfully larger
 * bill than the 3-fixture harness; console output reports elapsed time and
 * per-case turn counts so that's visible before deciding to re-run.
 *
 * Run: node --import tsx --env-file=.env.local scripts/verification/runCaseReviews.ts
 * (wired as `npm run test:case-reviews`)
 */

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { runStoryThroughPipeline, type PipelineRun } from "./fixtures/pipelineRunner";
import {
  PIPELINE_JOURNEY_TIMEOUT_MS,
  withTimeout,
  describeRunDegradation,
  abortIfRateLimited,
} from "./pipelineGuards";
import type { Fixture } from "./fixtures/fixtureTypes";
import { CASE_REVIEW_FIXTURES } from "./fixtures/caseReviews/caseReviewFixtures";
import { assertNotProduction } from "../db/assertNotProduction";

const OUTPUT_DIR = path.join(__dirname, "fixtures", "caseReviews", "output");

function renderCaseReviewMarkdown(fixture: Fixture, description: string, run: PipelineRun): string {
  const { turns, halted, haltMessage, intakeComplete, finalFacts, retainedMatchedClaimType, mappedInput, analysisOutput } = run;
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push(`# Case review: ${fixture.title}`);
  push();
  push(`**Fixture id:** \`${fixture.id}\``);
  push(`**What this case tests:** ${description}`);
  push(`**Location given:** ${fixture.location.city}, ${fixture.location.province}`);
  push();
  push(`Generated by \`npm run test:case-reviews\` against the real pipeline (real OpenAI calls, no mocks). All parties, dates, amounts and documents are fabricated. Not hand-edited after generation.`);
  push();

  push(`## 1. Documents in the file`);
  push();
  if (fixture.evidenceItems.length === 0) {
    push("_No documents recorded for this case._");
  } else {
    push(`| # | Filename | Type | Description |`);
    push(`|---|---|---|---|`);
    fixture.evidenceItems.forEach((item, i) => {
      push(`| ${i + 1} | \`${item.filename}\` | ${item.type} | ${item.description} |`);
    });
  }
  push();

  push(`## 2. Opening story (as the user typed it)`);
  push();
  push(`> ${fixture.story.replace(/\n/g, "\n> ")}`);
  push();

  push(`## 3. Full conversation -- every question asked and answered`);
  push();
  push(`halted: ${halted}${halted ? ` -- ${haltMessage}` : ""}`);
  push(`intakeComplete: ${intakeComplete}`);
  push(`turns run: ${turns.length}`);
  push();
  turns.forEach((t, i) => {
    if (t.questionAsked === null) {
      push(`**Turn ${i + 1} -- opening story.**`);
    } else {
      push(`**Turn ${i + 1} -- \`${t.questionAsked}\`**`);
      if (t.leadInShown) push(`> _${t.leadInShown}_`);
      push(`> **Question shown to user:** ${t.questionTextShown ?? "(text not captured)"}`);
    }
    push(`> **Answer given:** ${t.answerGiven ?? "(none)"}`);
    if (t.matchedClaimTypeThisTurn) push(`- Claim type matched this turn: ${t.matchedClaimTypeThisTurn}`);
    if (t.suggestedClaimTypeThisTurn) push(`- AI-suggested claim type this turn (not yet confirmed): ${t.suggestedClaimTypeThisTurn}`);
    if (t.evidenceGuidanceThisTurn) {
      push(`- Evidence guidance shown this turn: ${t.evidenceGuidanceThisTurn.categories.join(", ") || "(none)"}`);
    }
    if (t.possibleCorrections.length) {
      push(`- Possible corrections logged (proposed only, never auto-applied): ${t.possibleCorrections.join("; ")}`);
    }
    push();
  });

  push(`## 4. Claim type retained at the end of intake`);
  push();
  push(retainedMatchedClaimType ? `${retainedMatchedClaimType.claimTypeId} (${retainedMatchedClaimType.claimTypeName})` : "(none matched)");
  push();

  push(`## 5. Final recorded facts`);
  push();
  push("```json");
  push(JSON.stringify(finalFacts, null, 2));
  push("```");
  push();

  if (mappedInput) {
    push(`## 6. What was handed to the analysis engine`);
    push();
    push(`- **Amount claimed:** ${mappedInput.amountClaimed}`);
    push(`- **Timeline:** ${mappedInput.timeline}`);
    push(`- **Evidence, as recorded:** ${mappedInput.evidence}`);
    push(`- **Remedy/goal sought:** ${mappedInput.goal}`);
    push(`- **Service details:** ${mappedInput.serviceDetails || "(none)"}`);
    push(`- **Issues detected going in:** ${JSON.stringify(mappedInput.issues)}`);
    push();
  }

  if (analysisOutput) {
    const a = analysisOutput.analysis;
    push(`## 7. Full final case analysis (what the site actually produced)`);
    push();
    push(`**Detected issues:** ${JSON.stringify(a.detectedIssues)}`);
    push(`**Detected claim types:** ${JSON.stringify(a.detectedClaimTypes)}`);
    push();
    push(`**Missing information:**`);
    push(a.missingInformation.length ? a.missingInformation.map((s) => `- ${s}`).join("\n") : "_(none)_");
    push();
    const missingEvidence = a.missingEvidence ?? [];
    const risksAndGaps = a.risksAndGaps ?? [];
    const userWarnings = a.userWarnings ?? [];
    const nextBestActions = a.nextBestActions ?? [];
    push(`**Missing evidence:**`);
    push(missingEvidence.length ? missingEvidence.map((s) => `- ${s}`).join("\n") : "_(none)_");
    push();
    push(`**Risks and gaps:**`);
    push(risksAndGaps.length ? risksAndGaps.map((s) => `- ${s}`).join("\n") : "_(none)_");
    push();
    push(`**User warnings:**`);
    push(userWarnings.length ? userWarnings.map((s) => `- ${s}`).join("\n") : "_(none)_");
    push();
    push(`**Next best actions shown to the user:**`);
    push(nextBestActions.length ? nextBestActions.map((s) => `- ${s}`).join("\n") : "_(none)_");
    push();
    push(`**Plain-language case summary:**`);
    push(`> ${a.intelligenceSummary}`);
    push();
    push(`**Structured case summary:**`);
    push(`> ${a.structuredIntelligenceSummary}`);
    push();
  } else {
    push(`## 7. Full final case analysis`);
    push();
    push(halted ? "Not run -- conversation halted before completion." : "Not run.");
    push();
  }

  return lines.join("\n") + "\n";
}

function renderIndexMarkdown(
  results: Array<{ fixture: Fixture; description: string; outFile: string; run: PipelineRun | null; error: string | null }>,
): string {
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);
  push(`# Case review batch -- index`);
  push();
  push(`Generated by \`npm run test:case-reviews\`. ${results.length} fabricated full-case scenarios run end to end through the real pipeline.`);
  push();
  push(`| # | Case | What it tests | Turns | Claim type matched | Status |`);
  push(`|---|---|---|---|---|---|`);
  results.forEach((r, i) => {
    const status = r.error ? `FAILED: ${r.error}` : r.run?.halted ? `Halted: ${r.run.haltMessage}` : "Completed";
    const turns = r.run?.turns.length ?? "-";
    const claimType = r.run?.retainedMatchedClaimType?.claimTypeId ?? "-";
    push(`| ${i + 1} | [${r.fixture.title}](./output/${r.outFile}) | ${r.description} | ${turns} | ${claimType} | ${status} |`);
  });
  push();
  return lines.join("\n") + "\n";
}

async function main() {
  assertNotProduction("test:case-reviews");

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("OPENAI_API_KEY not set -- run with --env-file=.env.local");
    process.exitCode = 1;
    return;
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const startedAt = Date.now();
  const indexRows: Array<{ fixture: Fixture; description: string; outFile: string; run: PipelineRun | null; error: string | null }> = [];
  const failures: { id: string; reason: string }[] = [];

  for (const { fixture, description } of CASE_REVIEW_FIXTURES) {
    console.log(`\n${"=".repeat(70)}\nRunning case review: ${fixture.id}\n${"=".repeat(70)}`);
    const outFile = `${fixture.id}.review.md`;

    let run: PipelineRun;
    try {
      run = await withTimeout(runStoryThroughPipeline(fixture, apiKey), PIPELINE_JOURNEY_TIMEOUT_MS);
    } catch (error) {
      abortIfRateLimited(error, `case review ${fixture.id}`);
      const reason = error instanceof Error ? error.message : String(error);
      failures.push({ id: fixture.id, reason });
      indexRows.push({ fixture, description, outFile, run: null, error: reason });
      console.error(`  FAILED (not written): ${reason}`);
      continue; // unlike runFixtures.ts, one bad case shouldn't block the other 9 -- these aren't pinned regressions.
    }

    const degraded = describeRunDegradation(run);
    if (degraded) {
      failures.push({ id: fixture.id, reason: degraded });
      indexRows.push({ fixture, description, outFile, run, error: degraded });
      console.error(`  DEGRADED (written anyway, flagged in the file): ${degraded}`);
    } else {
      indexRows.push({ fixture, description, outFile, run, error: null });
    }

    const markdown = renderCaseReviewMarkdown(fixture, description, run);
    const outPath = path.join(OUTPUT_DIR, outFile);
    writeFileSync(outPath, markdown, "utf8");
    console.log(`  Wrote ${outPath}`);
    console.log(`  turns: ${run.turns.length}, halted: ${run.halted}, matchedClaimType: ${run.retainedMatchedClaimType?.claimTypeId ?? "(none)"}`);
  }

  const indexPath = path.join(__dirname, "fixtures", "caseReviews", "README.md");
  writeFileSync(indexPath, renderIndexMarkdown(indexRows), "utf8");
  console.log(`\nWrote index: ${indexPath}`);

  const elapsedS = Math.round((Date.now() - startedAt) / 1000);
  console.log(`\nRan ${CASE_REVIEW_FIXTURES.length} case review(s) in ${elapsedS}s. ${failures.length} failure(s).`);
  if (failures.length) {
    for (const f of failures) console.error(`  - ${f.id}: ${f.reason}`);
    process.exitCode = 1;
  }
}

const isDirect = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;

if (isDirect) {
  void main().catch((error: unknown) => {
    console.error("Case review batch threw:", error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
