/**
 * Session 35 -- runs the three whole-case fixtures in fixtures/ through the
 * REAL pipeline the app uses, end to end, and writes what actually happened
 * to fixtures/<id>.actual.md.
 *
 * Session 36: the turn-loop/mapping/analysis logic itself now lives in
 * fixtures/pipelineRunner.ts, shared with the new generated-story harness
 * (runGeneratedFixtures.ts) -- this file's own behavior and output are
 * unchanged by that extraction, just no longer duplicated.
 *
 * Real, billed OpenAI calls throughout (safety pass + extraction + voice
 * layer per turn with new text, the full structured-ai brain analysis at
 * the end) -- this is deliberate; the whole point of this harness is
 * testing the real pipeline, not a stub of it.
 *
 * Run: node --import tsx --env-file=.env.local scripts/verification/runFixtures.ts
 * (wired as `npm run test:fixtures`)
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { runStoryThroughPipeline, type PipelineRun } from "./fixtures/pipelineRunner";
import {
  PIPELINE_JOURNEY_TIMEOUT_MS,
  withTimeout,
  describeRunDegradation,
} from "./pipelineGuards";
import type { Fixture } from "./fixtures/fixtureTypes";
import { unpaidInvoiceCleanFixture } from "./fixtures/unpaidInvoiceClean.fixture";
import { unpaidInvoiceGapFixture } from "./fixtures/unpaidInvoiceGap.fixture";
import { overLimitContractFixture } from "./fixtures/overLimitContract.fixture";

const FIXTURES: Fixture[] = [unpaidInvoiceCleanFixture, unpaidInvoiceGapFixture, overLimitContractFixture];

function renderActualMarkdown(fixture: Fixture, run: PipelineRun): string {
  const { turns, halted, haltMessage, intakeComplete, finalFacts, retainedMatchedClaimType, mappedInput, analysisOutput } = run;
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  push(`# Actual: ${fixture.id}`);
  push("");
  push(`Generated by \`npm run test:fixtures\` against the real pipeline. Not hand-edited.`);
  push("");
  push(`## Conversation`);
  push("");
  push(`halted: ${halted}${halted ? ` -- ${haltMessage}` : ""}`);
  push(`intakeComplete: ${intakeComplete}`);
  push(`turns run: ${turns.length}`);
  push("");
  push(`| # | question asked | matched claim type this turn | evidenceGuidance this turn |`);
  push(`|---|---|---|---|`);
  turns.forEach((t, i) => {
    push(
      `| ${i + 1} | ${t.questionAsked ?? "(opening story)"} | ${t.matchedClaimTypeThisTurn ?? "-"} | ${
        t.evidenceGuidanceThisTurn
          ? `addressed: ${t.evidenceGuidanceThisTurn.addressed.join(", ") || "(none)"}; unaddressed: ${t.evidenceGuidanceThisTurn.unaddressed.join(", ") || "(none)"}`
          : "-"
      } |`,
    );
  });
  const corrections = turns.flatMap((t) => t.possibleCorrections);
  if (corrections.length) {
    push("");
    push(`possibleCorrections seen: ${corrections.join("; ")}`);
  }
  push("");
  push(`## Retained matchedClaimType at completion`);
  push("");
  push(retainedMatchedClaimType ? `${retainedMatchedClaimType.claimTypeId} (${retainedMatchedClaimType.claimTypeName})` : "(none)");
  push("");
  push(`## Final facts`);
  push("");
  push("```json");
  push(JSON.stringify(finalFacts, null, 2));
  push("```");

  if (mappedInput) {
    push("");
    push(`## mapGuidedIntakeToSmallClaimsInput() output (fields relevant to this harness)`);
    push("");
    push(`amountClaimed: ${JSON.stringify(mappedInput.amountClaimed)}`);
    push(`timeline: ${JSON.stringify(mappedInput.timeline)}`);
    push(`evidence: ${JSON.stringify(mappedInput.evidence)}`);
    push(`goal: ${JSON.stringify(mappedInput.goal)}`);
    push(`serviceDetails: ${JSON.stringify(mappedInput.serviceDetails)}`);
    push(`issues: ${JSON.stringify(mappedInput.issues)}`);
  }

  if (analysisOutput) {
    const a = analysisOutput.analysis;
    push("");
    push(`## Final AnalysisResult (analyzeSmallClaimsWithBrain, allowExternalCognition: true)`);
    push("");
    push(`detectedIssues: ${JSON.stringify(a.detectedIssues)}`);
    push(`detectedClaimTypes: ${JSON.stringify(a.detectedClaimTypes)}`);
    push(`missingInformation: ${JSON.stringify(a.missingInformation)}`);
    push(`missingEvidence: ${JSON.stringify(a.missingEvidence)}`);
    push(`risksAndGaps: ${JSON.stringify(a.risksAndGaps)}`);
    push(`userWarnings: ${JSON.stringify(a.userWarnings)}`);
    push(`intelligenceWarnings: ${JSON.stringify(a.intelligenceWarnings)}`);
    push(`proceduralRisks: ${JSON.stringify(a.proceduralRisks)}`);
    push(`nextBestActions: ${JSON.stringify(a.nextBestActions)}`);
    push(`intelligenceSummary: ${JSON.stringify(a.intelligenceSummary)}`);
    push(`structuredIntelligenceSummary: ${JSON.stringify(a.structuredIntelligenceSummary)}`);
  } else {
    push("");
    push(`## Final AnalysisResult`);
    push("");
    push(halted ? "Not run -- conversation halted before completion." : "Not run.");
  }

  return lines.join("\n") + "\n";
}

async function main() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("OPENAI_API_KEY not set -- run with --env-file=.env.local");
    process.exitCode = 1;
    return;
  }

  const failures: { id: string; reason: string }[] = [];

  for (const fixture of FIXTURES) {
    console.log(`\n${"=".repeat(70)}\nRunning fixture: ${fixture.id}\n${"=".repeat(70)}`);

    // Everything that can fail happens BEFORE the write. A throw, a timeout,
    // or a silently-degraded run leaves the committed .actual.md untouched,
    // because writeFileSync is only reached once `run` is known good.
    let run: PipelineRun;
    try {
      run = await withTimeout(
        runStoryThroughPipeline(fixture, apiKey),
        PIPELINE_JOURNEY_TIMEOUT_MS,
      );
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      failures.push({ id: fixture.id, reason });
      console.error(`  FAILED (not written): ${reason}`);
      break;
    }

    // The pipeline swallows API failures in two places and returns a run that
    // looks ordinary. Writing placeholder text over a good .actual.md would be
    // worse than not writing at all: it reads as real pipeline behaviour and
    // would be diffed against .expected.md as if it were.
    const degraded = describeRunDegradation(run);
    if (degraded) {
      failures.push({ id: fixture.id, reason: degraded });
      console.error(`  DEGRADED (not written): ${degraded}`);
      break;
    }

    const markdown = renderActualMarkdown(fixture, run);
    const outPath = path.join(__dirname, "fixtures", `${toFileId(fixture.id)}.actual.md`);
    writeFileSync(outPath, markdown, "utf8");
    console.log(`Wrote ${outPath}`);
    console.log(`  turns: ${run.turns.length}, halted: ${run.halted}, matchedClaimType: ${run.retainedMatchedClaimType?.claimTypeId ?? "(none)"}`);
  }

  if (failures.length) {
    console.error(
      `\n${"!".repeat(70)}\n` +
        `FIXTURE RUN ABORTED — ${failures.length} failure(s). No .actual.md was written\n` +
        `for the failing fixture, and any fixture after it was not attempted, so the\n` +
        `committed files are NOT a mixed record of one good run and one bad one.\n` +
        `${"!".repeat(70)}`,
    );
    for (const f of failures) console.error(`  - ${f.id}: ${f.reason}`);
    process.exitCode = 1;
    return;
  }

  console.log(`\nAll ${FIXTURES.length} fixture(s) ran and were written.`);
}

/** Fixture ids are kebab-case ("unpaid-invoice-clean"); files are camelCase, matching the .fixture.ts/.expected.md naming already committed. */
function toFileId(fixtureId: string): string {
  return fixtureId.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

// Entrypoint guard — runFullClaimTypeSurvey.ts lacked one and importing it
// silently re-ran 19 billed journeys. This harness bills three full fixtures
// (~130 requests), and the OpenAI project is capped per day, so an accidental
// import must not spend that. The explicit .catch() also replaces the previous
// bare main() call, whose rejection was left to Node's unhandled-rejection
// handler.
const isDirect = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;

if (isDirect) {
  void main().catch((error: unknown) => {
    console.error("Fixture harness threw:", error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
