/**
 * Session 35 -- runs the three whole-case fixtures in fixtures/ through the
 * REAL pipeline the app uses, end to end, and writes what actually happened
 * to fixtures/<id>.actual.md.
 *
 * Session 36: the turn-loop/mapping/analysis logic itself now lives in
 * fixtures/pipelineRunner.ts, shared with the new generated-story harness
 * (runGeneratedFixtures.ts) -- this file's own behavior and output are
 * unchanged by that extraction, just no longer duplicated.
 *
 * Real, billed OpenAI calls throughout (safety pass + extraction + voice
 * layer per turn with new text, the full structured-ai brain analysis at
 * the end) -- this is deliberate; the whole point of this harness is
 * testing the real pipeline, not a stub of it.
 *
 * Run: node --import tsx --env-file=.env.local scripts/verification/runFixtures.ts
 * (wired as `npm run test:fixtures`)
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

import { runStoryThroughPipeline, type PipelineRun } from "./fixtures/pipelineRunner";
import type { Fixture } from "./fixtures/fixtureTypes";
import { unpaidInvoiceCleanFixture } from "./fixtures/unpaidInvoiceClean.fixture";
import { unpaidInvoiceGapFixture } from "./fixtures/unpaidInvoiceGap.fixture";
import { overLimitContractFixture } from "./fixtures/overLimitContract.fixture";

const FIXTURES: Fixture[] = [unpaidInvoiceCleanFixture, unpaidInvoiceGapFixture, overLimitContractFixture];

function renderActualMarkdown(fixture: Fixture, run: PipelineRun): string {
  const { turns, halted, haltMessage, intakeComplete, finalFacts, retainedMatchedClaimType, mappedInput, analysisOutput } = run;
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  push(`# Actual: ${fixture.id}`);
  push("");
  push(`Generated by \`npm run test:fixtures\` against the real pipeline. Not hand-edited.`);
  push("");
  push(`## Conversation`);
  push("");
  push(`halted: ${halted}${halted ? ` -- ${haltMessage}` : ""}`);
  push(`intakeComplete: ${intakeComplete}`);
  push(`turns run: ${turns.length}`);
  push("");
  push(`| # | question asked | matched claim type this turn | evidenceGuidance this turn |`);
  push(`|---|---|---|---|`);
  turns.forEach((t, i) => {
    push(
      `| ${i + 1} | ${t.questionAsked ?? "(opening story)"} | ${t.matchedClaimTypeThisTurn ?? "-"} | ${
        t.evidenceGuidanceThisTurn
          ? `addressed: ${t.evidenceGuidanceThisTurn.addressed.join(", ") || "(none)"}; unaddressed: ${t.evidenceGuidanceThisTurn.unaddressed.join(", ") || "(none)"}`
          : "-"
      } |`,
    );
  });
  const corrections = turns.flatMap((t) => t.possibleCorrections);
  if (corrections.length) {
    push("");
    push(`possibleCorrections seen: ${corrections.join("; ")}`);
  }
  push("");
  push(`## Retained matchedClaimType at completion`);
  push("");
  push(retainedMatchedClaimType ? `${retainedMatchedClaimType.claimTypeId} (${retainedMatchedClaimType.claimTypeName})` : "(none)");
  push("");
  push(`## Final facts`);
  push("");
  push("```json");
  push(JSON.stringify(finalFacts, null, 2));
  push("```");

  if (mappedInput) {
    push("");
    push(`## mapGuidedIntakeToSmallClaimsInput() output (fields relevant to this harness)`);
    push("");
    push(`amountClaimed: ${JSON.stringify(mappedInput.amountClaimed)}`);
    push(`timeline: ${JSON.stringify(mappedInput.timeline)}`);
    push(`evidence: ${JSON.stringify(mappedInput.evidence)}`);
    push(`goal: ${JSON.stringify(mappedInput.goal)}`);
    push(`serviceDetails: ${JSON.stringify(mappedInput.serviceDetails)}`);
    push(`issues: ${JSON.stringify(mappedInput.issues)}`);
  }

  if (analysisOutput) {
    const a = analysisOutput.analysis;
    push("");
    push(`## Final AnalysisResult (analyzeSmallClaimsWithBrain, allowExternalCognition: true)`);
    push("");
    push(`detectedIssues: ${JSON.stringify(a.detectedIssues)}`);
    push(`detectedClaimTypes: ${JSON.stringify(a.detectedClaimTypes)}`);
    push(`missingInformation: ${JSON.stringify(a.missingInformation)}`);
    push(`missingEvidence: ${JSON.stringify(a.missingEvidence)}`);
    push(`evidenceWeaknesses: ${JSON.stringify(a.evidenceWeaknesses)}`);
    push(`risksAndGaps: ${JSON.stringify(a.risksAndGaps)}`);
    push(`userWarnings: ${JSON.stringify(a.userWarnings)}`);
    push(`intelligenceWarnings: ${JSON.stringify(a.intelligenceWarnings)}`);
    push(`judgeConcerns: ${JSON.stringify(a.judgeConcerns)}`);
    push(`courtConcerns: ${JSON.stringify(a.courtConcerns)}`);
    push(`proceduralRisks: ${JSON.stringify(a.proceduralRisks)}`);
    push(`nextBestActions: ${JSON.stringify(a.nextBestActions)}`);
    push(`intelligenceSummary: ${JSON.stringify(a.intelligenceSummary)}`);
  } else {
    push("");
    push(`## Final AnalysisResult`);
    push("");
    push(halted ? "Not run -- conversation halted before completion." : "Not run.");
  }

  return lines.join("\n") + "\n";
}

async function main() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("OPENAI_API_KEY not set -- run with --env-file=.env.local");
    process.exitCode = 1;
    return;
  }

  for (const fixture of FIXTURES) {
    console.log(`\n${"=".repeat(70)}\nRunning fixture: ${fixture.id}\n${"=".repeat(70)}`);
    const run = await runStoryThroughPipeline(fixture, apiKey);
    const markdown = renderActualMarkdown(fixture, run);
    const outPath = path.join(__dirname, "fixtures", `${toFileId(fixture.id)}.actual.md`);
    writeFileSync(outPath, markdown, "utf8");
    console.log(`Wrote ${outPath}`);
    console.log(`  turns: ${run.turns.length}, halted: ${run.halted}, matchedClaimType: ${run.retainedMatchedClaimType?.claimTypeId ?? "(none)"}`);
  }
}

/** Fixture ids are kebab-case ("unpaid-invoice-clean"); files are camelCase, matching the .fixture.ts/.expected.md naming already committed. */
function toFileId(fixtureId: string): string {
  return fixtureId.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

main();
