/**
 * Runs the three existing unpaid-invoice-shaped fixtures through the real
 * pipeline (via pipelineRunner.ts, the same shared runner runFixtures.ts
 * and runGeneratedFixtures.ts already use -- no second, independently
 * maintained copy of that turn-loop logic) and then through the new
 * statementOfClaimDraftEngine.ts, writing each result to
 * fixtures/<id>.draft.md -- same output-file convention runFixtures.ts
 * already uses for .actual.md.
 *
 * Deliberately a separate script rather than a change to runFixtures.ts
 * itself: that file is CI-wired (`npm run test:fixtures`) and its existing
 * .actual.md output is a real, relied-on regression surface. This script
 * reuses its infrastructure (pipelineRunner.ts, the fixture files) without
 * touching its behavior.
 *
 * Real, billed OpenAI calls throughout, same as runFixtures.ts -- the
 * point is testing the real pipeline's output, not a stub of it.
 *
 * Run: node --import tsx --env-file=.env.local scripts/verification/runFixtureDrafts.ts
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

import { runStoryThroughPipeline, type PipelineRun } from "./fixtures/pipelineRunner";
import type { Fixture } from "./fixtures/fixtureTypes";
import { unpaidInvoiceCleanFixture } from "./fixtures/unpaidInvoiceClean.fixture";
import { unpaidInvoiceGapFixture } from "./fixtures/unpaidInvoiceGap.fixture";
import { overLimitContractFixture } from "./fixtures/overLimitContract.fixture";
import { draftStatementOfClaimParticulars } from "../../src/lib/case-system/statementOfClaimDraftEngine";

const FIXTURES: Fixture[] = [unpaidInvoiceCleanFixture, unpaidInvoiceGapFixture, overLimitContractFixture];

function renderDraftMarkdown(fixture: Fixture, run: PipelineRun): string {
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  push(`# Statement of Claim draft: ${fixture.id}`);
  push("");
  push("Generated by `runFixtureDrafts.ts` against the real pipeline's output. Not hand-edited.");
  push("");

  if (run.halted) {
    push(`Pipeline halted before completion: ${run.haltMessage}`);
    push("No draft was generated.");
    return lines.join("\n") + "\n";
  }

  if (!run.mappedInput) {
    push("No mapped input was produced (pipeline did not complete). No draft was generated.");
    return lines.join("\n") + "\n";
  }

  push(`## Matched claim type`);
  push("");
  push(
    run.retainedMatchedClaimType
      ? `${run.retainedMatchedClaimType.claimTypeId} (${run.retainedMatchedClaimType.claimTypeName})`
      : "(none)",
  );
  push("");

  push(`## Source facts this draft was built from (SmallClaimsIntelligenceInput, mapped from the guided intake)`);
  push("");
  push("```json");
  push(
    JSON.stringify(
      {
        yourName: run.mappedInput.yourName,
        yourAddress: run.mappedInput.yourAddress,
        otherParty: run.mappedInput.otherParty,
        defendantAddress: run.mappedInput.defendantAddress,
        amountClaimed: run.mappedInput.amountClaimed,
        facts: run.mappedInput.facts,
        timeline: run.mappedInput.timeline,
        goal: run.mappedInput.goal,
      },
      null,
      2,
    ),
  );
  push("```");
  push("");

  const draft = draftStatementOfClaimParticulars(run.mappedInput, run.retainedMatchedClaimType);

  push(`## missingParticulars`);
  push("");
  push(draft.missingParticulars.length ? draft.missingParticulars.map((item) => `- ${item}`).join("\n") : "(none)");
  push("");

  push(`## Full draftText`);
  push("");
  push("```");
  push(draft.draftText);
  push("```");

  return lines.join("\n") + "\n";
}

async function main() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("OPENAI_API_KEY not set -- run with --env-file=.env.local");
    process.exitCode = 1;
    return;
  }

  for (const fixture of FIXTURES) {
    console.log(`\n${"=".repeat(70)}\nDrafting from fixture: ${fixture.id}\n${"=".repeat(70)}`);
    const run = await runStoryThroughPipeline(fixture, apiKey);
    const markdown = renderDraftMarkdown(fixture, run);
    const outPath = path.join(__dirname, "fixtures", `${toFileId(fixture.id)}.draft.md`);
    writeFileSync(outPath, markdown, "utf8");
    console.log(`Wrote ${outPath}`);
  }
}

/** Fixture ids are kebab-case ("unpaid-invoice-clean"); files are camelCase, matching runFixtures.ts's own toFileId(). */
function toFileId(fixtureId: string): string {
  return fixtureId.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

main();
