/**
 * Session 36 -- scales Session 35's fixture harness from 3 hand-written
 * fixtures to a generated batch, checked against rules instead of one
 * hand-written expectation per story.
 *
 * Same real pipeline, no shortcuts, no mocks: every story runs through
 * fixtures/pipelineRunner.ts's runStoryThroughPipeline() -- the identical
 * orchestrateIntakeTurn() -> mapGuidedIntakeToSmallClaimsInput() ->
 * analyzeSmallClaimsWithBrain() chain runFixtures.ts uses for the 3
 * hand-written fixtures.
 *
 * The 5 rules (fixtures/ruleChecks.ts) come directly from real failures
 * Session 35 found and Session 36's fix addressed -- no new rules invented
 * here. Every check is a deterministic pattern match; nothing here ever
 * asks an AI to judge another AI's output.
 *
 * Writes ONE summary report (generatedStoriesReport.md) with the pass
 * rate and, for every failure, which rule and the exact offending text --
 * not summarized away.
 *
 * Run: node --import tsx --env-file=.env.local scripts/verification/runGeneratedFixtures.ts [count]
 * (wired as `npm run test:fixtures:generated`, defaults to 50)
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

import { runStoryThroughPipeline } from "./fixtures/pipelineRunner";
import { generateStories } from "./fixtures/generateStories";
import { checkRules, type RuleCheckResult, type RuleFailure } from "./fixtures/ruleChecks";

const RULE_LABELS: Record<string, string> = {
  "no-judge-prediction": "Rule 1: No judge-prediction language",
  "no-opposing-argument-prediction": "Rule 2: No opposing-argument-prediction language",
  "confirmed-evidence-not-missing": "Rule 3: Confirmed evidence must not be flagged missing",
  "over-limit-warning-correct": "Rule 4: Over-limit warning must fire iff amount exceeds the limit",
  "uncertain-date-preserved": "Rule 5: Uncertain dates must be preserved as uncertain",
};

function renderReport(results: RuleCheckResult[], count: number, startedAt: number): string {
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  const passed = results.filter((r) => r.failures.length === 0);
  const failed = results.filter((r) => r.failures.length > 0);
  const totalFailures = results.reduce((sum, r) => sum + r.failures.length, 0);

  const byRule = new Map<string, number>();
  for (const r of results) {
    for (const f of r.failures) byRule.set(f.rule, (byRule.get(f.rule) || 0) + 1);
  }

  const byClaimType = new Map<string, number>();
  for (const r of results) byClaimType.set(r.claimTypeId, (byClaimType.get(r.claimTypeId) || 0) + 1);

  push(`# Generated stories report (${count} stories)`);
  push("");
  push(`Generated by \`npm run test:fixtures:generated\` against the real pipeline. Not hand-edited.`);
  push(`Run duration: ${Math.round((Date.now() - startedAt) / 1000)}s`);
  push("");
  push(`## Summary`);
  push("");
  push(`**Pass rate: ${passed.length}/${count} (${Math.round((passed.length / count) * 100)}%)**`);
  push(`Stories with at least one rule failure: ${failed.length}`);
  push(`Total individual rule failures: ${totalFailures}`);
  push("");
  push(`### Failures by rule`);
  push("");
  if (byRule.size === 0) {
    push("None.");
  } else {
    for (const [rule, n] of [...byRule.entries()].sort((a, b) => b[1] - a[1])) {
      push(`- ${RULE_LABELS[rule] || rule}: ${n}`);
    }
  }
  push("");
  push(`### Claim types exercised (ground truth -- which archetype each story was built from)`);
  push("");
  for (const [claimType, n] of [...byClaimType.entries()].sort()) {
    push(`- ${claimType}: ${n} stories`);
  }
  push("");
  push(`### Actual claim-type match vs. ground truth`);
  push("");
  const matchMismatches = results.filter((r) => r.matchedClaimType !== r.claimTypeId);
  push(`Stories where the real matchClaimType() result differed from the archetype's intended claim type: ${matchMismatches.length}/${count}`);
  if (matchMismatches.length > 0) {
    for (const r of matchMismatches) {
      push(`- ${r.storyId}: expected ${r.claimTypeId}, matched ${r.matchedClaimType ?? "(none)"}`);
    }
  }
  push("");
  push(`## Failures, in full`);
  push("");
  if (failed.length === 0) {
    push("None.");
  } else {
    for (const r of failed) {
      push(`### ${r.storyId} (claimTypeId: ${r.claimTypeId}, matched: ${r.matchedClaimType ?? "(none)"})`);
      push("");
      for (const f of r.failures) {
        push(`- **${RULE_LABELS[f.rule] || f.rule}**`);
        push(`  - ${f.detail}`);
        push(`  - Offending text: \`${f.offendingText.replace(/`/g, "'")}\``);
      }
      push("");
    }
  }

  return lines.join("\n") + "\n";
}

async function main() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("OPENAI_API_KEY not set -- run with --env-file=.env.local");
    process.exitCode = 1;
    return;
  }

  const count = Number(process.argv[2]) || 50;
  const startedAt = Date.now();
  const stories = generateStories(count);
  const results: RuleCheckResult[] = [];

  for (let i = 0; i < stories.length; i += 1) {
    const story = stories[i];
    console.log(`[${i + 1}/${stories.length}] Running ${story.id} (claimTypeId=${story.claimTypeId}, amount=$${story.amount.toLocaleString()}, overLimit=${story.overLimit}, dateUncertain=${story.dateUncertain})`);
    try {
      const run = await runStoryThroughPipeline(story, apiKey);
      if (run.halted || !run.analysisOutput) {
        results.push({
          storyId: story.id,
          claimTypeId: story.claimTypeId,
          matchedClaimType: run.retainedMatchedClaimType?.claimTypeId ?? null,
          failures: [
            {
              rule: "over-limit-warning-correct",
              detail: run.halted ? `Conversation halted: ${run.haltMessage}` : "No analysis output produced",
              offendingText: "(no analysis output to check)",
            } as RuleFailure,
          ],
        });
        continue;
      }
      const result = checkRules(story, run.analysisOutput.analysis, run.retainedMatchedClaimType?.claimTypeId ?? null);
      results.push(result);
      console.log(`  -> ${result.failures.length === 0 ? "PASS" : `${result.failures.length} failure(s)`}`);
    } catch (error) {
      console.error(`  -> ERROR: ${error instanceof Error ? error.message : String(error)}`);
      results.push({
        storyId: story.id,
        claimTypeId: story.claimTypeId,
        matchedClaimType: null,
        failures: [
          {
            rule: "over-limit-warning-correct",
            detail: `Threw during pipeline run: ${error instanceof Error ? error.message : String(error)}`,
            offendingText: "(exception, no output to check)",
          } as RuleFailure,
        ],
      });
    }
  }

  const report = renderReport(results, count, startedAt);
  const outPath = path.join(__dirname, "fixtures", "generatedStoriesReport.md");
  writeFileSync(outPath, report, "utf8");
  console.log(`\nWrote ${outPath}`);
  const passed = results.filter((r) => r.failures.length === 0).length;
  console.log(`Pass rate: ${passed}/${results.length}`);
}

main();
